// GENERATED by @gel/generate v0.6.2

import type {Executor} from "gel";

export type SeedArgs = {
  readonly "rep_email": string;
  readonly "rep_ucard_number": number;
  readonly "rep_username": string;
  readonly "user_email": string;
  readonly "user_ucard_number": number;
  readonly "user_username": string;
};

export type SeedReturns = [({
  "id": string;
}), ...({
  "id": string;
})[]];

export function seed(client: Executor, args: SeedArgs): Promise<SeedReturns> {
  return client.queryRequired(`\
with
    rep_training := (insert training::Training {
        name := "Rep training",
        in_person := false,
        description := "",
    }),
    rep_training_in_person := (insert training::Training {
        name := "In person training",
        in_person := true,
        description := "",
        expires_after := <cal::relative_duration>"-1 second",
    }),
    training := insert training::Training {
        name := "Training",
        in_person := false,
        description := "",
        rep := rep_training,
    },
    in_person_training := insert training::Training {
        name := "In person training",
        in_person := true,
        description := "",
        rep := rep_training,
    },
    training_with_rep_in_person_rep := insert training::Training {
        name := "Training",
        in_person := false,
        description := "",
        rep := rep_training_in_person,
    },
    in_person_with_in_person_rep_training := insert training::Training {
        name := "In person with in person rep training",
        in_person := true,
        description := "",
        rep := rep_training_in_person,
    },
select {
    insert users::User {
        first_name := "User",
        display_name := "User",
        email := <str>$user_email,
        organisational_unit := "IPE",
        ucard_number := <int32>$user_ucard_number,
        username := <str>$user_username,
        training := assert_distinct((
            with training_items := {
                training,
                in_person_training,
                in_person_with_in_person_rep_training,
            },
            for training in training_items union (
                select training { @created_at := datetime_of_statement() }
            )
        )),
    },
    insert users::Rep {
        first_name := "Rep",
        display_name := "Rep",
        email := <str>$rep_email,
        organisational_unit := "IPE",
        ucard_number := <int32>$rep_ucard_number,
        username := <str>$rep_username,
        teams := assert_distinct((
            for team in (insert team::Team { name := "Test", description := "" }) union (
                select team { @created_at := datetime_of_statement() }
            )
        )),
        training := assert_distinct((
            with training_items := {
                rep_training,
                rep_training_in_person,
                training,
                in_person_training,
                training_with_rep_in_person_rep,
                in_person_with_in_person_rep_training,
            },
            for training in training_items union (
                select training { @created_at := datetime_of_statement() }
            )
        )),
    },
}`, args);

}
