// GENERATED by @gel/generate v0.6.2

import * as $ from "../../reflection";
import * as _ from "../../imports";
import type * as _shop from "../shop";
import type * as _std from "../std";
export type $CuboidλShape = $.typeutil.flatten<_shop.$DimensionλShape & {
  "height": $.PropertyDesc<_std.$int64, $.Cardinality.One, false, false, false, false>;
  "length": $.PropertyDesc<_std.$int64, $.Cardinality.One, false, false, false, false>;
  "unit": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "width": $.PropertyDesc<_std.$int64, $.Cardinality.One, false, false, false, false>;
  "formatted": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
}>;
type $Cuboid = $.ObjectType<"shop::dimensions::Cuboid", $CuboidλShape, null, [
  ..._shop.$Dimension['__exclusives__'],
], "shop::dimensions::Cuboid">;
const $Cuboid = $.makeType<$Cuboid>(_.spec, "1840b169-b9ee-11f0-830c-11a627161442", _.syntax.literal);

const Cuboid: $.$expr_PathNode<$.TypeSet<$Cuboid, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Cuboid, $.Cardinality.Many), null);

export type $CylindricalλShape = $.typeutil.flatten<_shop.$DimensionλShape & {
  "diameter": $.PropertyDesc<_std.$int64, $.Cardinality.One, false, false, false, false>;
  "length": $.PropertyDesc<_std.$int64, $.Cardinality.One, false, false, false, false>;
  "unit": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "formatted": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
}>;
type $Cylindrical = $.ObjectType<"shop::dimensions::Cylindrical", $CylindricalλShape, null, [
  ..._shop.$Dimension['__exclusives__'],
], "shop::dimensions::Cylindrical">;
const $Cylindrical = $.makeType<$Cylindrical>(_.spec, "1844008b-b9ee-11f0-9491-c7417069fe5e", _.syntax.literal);

const Cylindrical: $.$expr_PathNode<$.TypeSet<$Cylindrical, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Cylindrical, $.Cardinality.Many), null);

export type $ISO216λShape = $.typeutil.flatten<_shop.$DimensionλShape & {
  "size": $.PropertyDesc<_std.$int16, $.Cardinality.One, false, false, false, false>;
  "unit": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "formatted": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
}>;
type $ISO216 = $.ObjectType<"shop::dimensions::ISO216", $ISO216λShape, null, [
  ..._shop.$Dimension['__exclusives__'],
], "shop::dimensions::ISO216">;
const $ISO216 = $.makeType<$ISO216>(_.spec, "1845fdf5-b9ee-11f0-9a66-65d9a36f24f2", _.syntax.literal);

const ISO216: $.$expr_PathNode<$.TypeSet<$ISO216, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($ISO216, $.Cardinality.Many), null);

export type $LiquidVolumeλShape = $.typeutil.flatten<_shop.$DimensionλShape & {
  "unit": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "volume": $.PropertyDesc<_std.$int64, $.Cardinality.One, false, false, false, false>;
  "formatted": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
}>;
type $LiquidVolume = $.ObjectType<"shop::dimensions::LiquidVolume", $LiquidVolumeλShape, null, [
  ..._shop.$Dimension['__exclusives__'],
], "shop::dimensions::LiquidVolume">;
const $LiquidVolume = $.makeType<$LiquidVolume>(_.spec, "1847b20a-b9ee-11f0-9271-d38800305e84", _.syntax.literal);

const LiquidVolume: $.$expr_PathNode<$.TypeSet<$LiquidVolume, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($LiquidVolume, $.Cardinality.Many), null);

export type $MassλShape = $.typeutil.flatten<_shop.$DimensionλShape & {
  "mass": $.PropertyDesc<_std.$int64, $.Cardinality.One, false, false, false, false>;
  "unit": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "formatted": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
}>;
type $Mass = $.ObjectType<"shop::dimensions::Mass", $MassλShape, null, [
  ..._shop.$Dimension['__exclusives__'],
], "shop::dimensions::Mass">;
const $Mass = $.makeType<$Mass>(_.spec, "18495360-b9ee-11f0-bb77-cd58cedd3797", _.syntax.literal);

const Mass: $.$expr_PathNode<$.TypeSet<$Mass, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Mass, $.Cardinality.Many), null);



export { $Cuboid, Cuboid, $Cylindrical, Cylindrical, $ISO216, ISO216, $LiquidVolume, LiquidVolume, $Mass, Mass };

type __defaultExports = {
  "Cuboid": typeof Cuboid;
  "Cylindrical": typeof Cylindrical;
  "ISO216": typeof ISO216;
  "LiquidVolume": typeof LiquidVolume;
  "Mass": typeof Mass
};
const __defaultExports: __defaultExports = {
  "Cuboid": Cuboid,
  "Cylindrical": Cylindrical,
  "ISO216": ISO216,
  "LiquidVolume": LiquidVolume,
  "Mass": Mass
};
export default __defaultExports;
