import { AppConfig } from "@/types/nav";
import {
  BellIcon,
  BookIcon,
  BookOpenIcon, BookUserIcon,
  ClipboardPenIcon,
  EarthIcon, FilePenIcon,
  FingerprintIcon,
  HouseIcon,
  LayoutDashboardIcon, MailIcon, MegaphoneIcon, MessageCircleIcon,
  PencilRulerIcon,
  PrinterIcon,
  RssIcon, SchoolIcon,
  ServerCrashIcon,
  ShieldAlertIcon, ShieldCheckIcon,
  TreePalmIcon,
  UserCogIcon, UsersIcon,
  ZapIcon,
} from "lucide-react";

export const appConfig: AppConfig[] = [
  {
    name: "Home",
    url: "/",
    logo: HouseIcon,
    color: "#115e59",
    description: "",
    mainMenuNavigable: true,
    routes: [
      {
        title: "Home",
        url: "/",
        icon: HouseIcon,
        isActive: true,
      },
    ],
    navSub: [
      { name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon, isExternal: true },
      { name: "LinkTree", url: "https://linktr.ee/iforgeuos", icon: TreePalmIcon, isExternal: true },
    ],
  },
  {
    name: "Sign In",
    url: "/sign-in/",
    logo: PencilRulerIcon,
    color: "#500724",
    description: "Manage your Sign-In data here.",
    mainMenuNavigable: true,
    routes: [
      {
        title: "Home",
        url: "/sign-in",
        icon: HouseIcon,
        isActive: true,
      },
      {
        title: "Agreements",
        url: "/sign-in/agreements",
        icon: ClipboardPenIcon,
        isActive: true,
      },
      {
        title: "Actions",
        icon: ZapIcon,
        isActive: true,
        requiredRoles: ["rep"],
        items: [
          {
            title: "Sign In",
            url: "/sign-in/actions/in",
          },
          {
            title: "Sign Out",
            url: "/sign-in/actions/out",
          },
          {
            title: "Enqueue",
            url: "/sign-in/actions/enqueue",
          },
        ],
        url: "",
      },
      {
        title: "Dashboard",
        url: "/sign-in/dashboard",
        icon: LayoutDashboardIcon,
        isActive: true,
        requiredRoles: ["rep"],
      },
    ],
    navSub: [{ name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon, isExternal: true }],
  },
  {
    name: "Training",
    url: "/training",
    color: "#022c22",
    logo: BookIcon,
    description: "Do your user training here.",
    mainMenuNavigable: true,
    routes: [
      {
        title: "Home",
        url: "/training",
        icon: HouseIcon,
        isActive: true,
      },
      {
        title: "Locations",
        icon: EarthIcon,
        isActive: true,
        items: [
          {
            title: "Mainspace",
            url: "/training/locations/mainspace",
          },
          {
            title: "Heartspace",
            url: "/training/locations/heartspace",
          },
        ],
        url: "",
      },
      {
        title: "Useful Links",
        icon: RssIcon,
        isActive: true,
        items: [
          {
            title: "Approved Materials",
            url: "/training/approved-materials",
          },
          {
            title: "Risk Assessments",
            url: "/training/risk-assessments",
          },
        ],
        url: "",
      },
    ],
    navSub: [{ name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon }],
  },
  {
    name: "Printing",
    url: "/printing",
    color: "#1e1b4b",
    logo: PrinterIcon,
    description: "Manage your 3D Print Jobs here (coming soon)",
    mainMenuNavigable: false,
    routes: [
      {
        title: "Home",
        url: "/printing",
        icon: HouseIcon,
        isActive: true,
      },
    ],
    navSub: [{ name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon }],
  },
  {
    name: "User",
    url: "/user",
    logo: UserCogIcon,
    color: "#701a75",
    description: "Manage your user details here",
    mainMenuNavigable: false,
    routes: [
      {
        title: "Home",
        url: "/user",
        icon: HouseIcon,
        isActive: true,
      },
    ],
    navSub: [{ name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon }],
  },
  {
    name: "Admin",
    url: "/admin",
    color: "#1e1b4b",
    logo: ShieldAlertIcon,
    description: "Administer the iForge",
    mainMenuNavigable: true,
    requiredRoles: ["admin"],
    routes: [
      {
        title: "Dashboard",
        url: "/admin/dashboard",
        icon: LayoutDashboardIcon,
        isActive: true,
      },
      {
        title: "Agreements",
        url: "/admin/agreements",
        icon: FilePenIcon,
        isActive: true,
      },
      {
        title: "Notifications",
        icon: BellIcon,
        url: "/admin/notifications/dashboard",
        isActive: true,
        items: [
          {
            title: "Emails",
            icon: MailIcon,
            url: "/admin/notifications/email",
          },
          {
            title: "App Notifications",
            icon: MegaphoneIcon,
            url: "/admin/notifications/app",
          },
          {
            title: "Discord",
            icon: MessageCircleIcon,
            url: "/admin/notifications/discord",
          },
        ],
      },
      {
        title: "Reps",
        url: "/admin/reps",
        icon: ShieldCheckIcon,
        isActive: true,
      },
      {
        title: "Teams",
        url: "/admin/teams",
        icon: UsersIcon,
        isActive: true,
      },
      {
        title: "Users",
        url: "/admin/users",
        icon: BookUserIcon,
        isActive: true,
      },
      {
        title: "Training",
        url: "/admin/training",
        icon: SchoolIcon,
        isActive: true,
      },
    ],
    navSub: [{ name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon }],
  },
  {
    name: "Auth",
    url: "/auth",
    color: "#b91c1c",
    logo: FingerprintIcon,
    description: "Authenticate with the iForge",
    mainMenuNavigable: false,
    routes: [],
    navSub: [{ name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon }],
  },
  {
    name: "Error",
    url: "",
    color: "#b45309",
    logo: ServerCrashIcon,
    description: "Oh no!",
    mainMenuNavigable: false,
    routes: [],
  },
  {
    name: "Socials",
    url: "/socials",
    color: "#fb7185",
    logo: RssIcon,
    description: "iForge Social Media Profiles",
    mainMenuNavigable: false,
    routes: [
      {
        title: "Home",
        url: "/socials",
        icon: HouseIcon,
        isActive: true,
      },
    ],
  },
];
