import {
  ArrowLeftToLineIcon,
  ArrowRightToLineIcon,
  BellIcon,
  BookIcon,
  BookOpenIcon,
  BookUserIcon,
  ClipboardPenIcon,
  DatabaseIcon,
  EarthIcon,
  FilePenIcon,
  FileWarningIcon,
  FingerprintIcon,
  HammerIcon,
  HeartIcon,
  HistoryIcon,
  HouseIcon,
  LayoutDashboardIcon,
  ListEndIcon,
  MailboxIcon,
  PartyPopperIcon,
  PencilRulerIcon,
  PrinterIcon,
  RssIcon,
  SchoolIcon,
  ScissorsLineDashedIcon,
  ServerCrashIcon,
  SettingsIcon,
  ShieldAlertIcon,
  ShieldCheckIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  StoreIcon,
  TrafficConeIcon,
  TreePalmIcon,
  TruckIcon,
  UndoIcon,
  UserCogIcon,
  UserIcon,
  UsersIcon,
  WrenchIcon,
  ZapIcon,
} from "lucide-react";
import { getActiveLocation } from "@/lib/utils/sign-in";
import { AppConfig } from "@/types/nav";
import { RepIcon } from "../icons/Rep";

export const appConfig: AppConfig[] = [
  {
    name: "Home",
    url: "/",
    logo: HouseIcon,
    color: "#115e59",
    description: "",
    mainMenuNavigable: true,
    routes: [
      {
        title: "Home",
        url: "/",
        icon: HouseIcon,
        isActive: true,
      },
      {
        title: "Locations",
        icon: EarthIcon,
        isActive: true,
        items: [
          {
            title: "Mainspace",
            icon: WrenchIcon,
            url: "/locations#mainspace",
          },
          {
            title: "Heartspace",
            icon: HeartIcon,
            url: "/locations#heartspace",
          },
        ],
      },
      {
        title: "Our Reps",
        url:"/our-reps",
        icon: RepIcon,
        isActive: true,
      },
      {
        title: "Events",
        url:"/events",
        icon: PartyPopperIcon,
        isActive: true,
      },
    ],
    navSub: [
      { name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon, isExternal: true },
      { name: "LinkTree", url: "https://linktr.ee/iforgeuos", icon: TreePalmIcon, isExternal: true },
    ],
  },
  {
    name: "Sign In",
    url: "/sign-in/$location",
    params: () => ({ location: getActiveLocation() }),
    logo: PencilRulerIcon,
    color: "#500724",
    description: "Manage sign-ins",
    mainMenuNavigable: true,
    routes: [
      {
        title: "Home",
        url: "/sign-in/$location",
        params: () => ({ location: getActiveLocation() }),
        icon: HouseIcon,
        isActive: true,
      },
            {
        title: "Dashboard",
        url: "/sign-in/$location/dashboard",
        params: () => ({ location: getActiveLocation() }),
        icon: LayoutDashboardIcon,
        isActive: true,
        requiredRoles: ["rep"],
      },
      // {
      //   title: "Actions",
      //   icon: ZapIcon,
      //   isActive: true,
      //   requiredRoles: ["rep"],
      //   items: [
      //     {
      //       title: "Sign In",
      //       icon: ArrowRightToLineIcon,
      //       url: "/sign-in/$location/actions/in",
      //       params: () => ({ location: getActiveLocation() }),
      //     },
      //     {
      //       title: "Sign Out",
      //       icon: ArrowLeftToLineIcon,
      //       url: "/sign-in/$location/actions/out",
      //       params: () => ({ location: getActiveLocation() }),
      //     },
      //     {
      //       title: "Enqueue",
      //       icon: ListEndIcon,
      //       url: "/sign-in/$location/actions/enqueue",
      //       params: () => ({ location: getActiveLocation() }),
      //     },
      //   ],
      // },
    ],
    navSub: [{ name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon, isExternal: true }],
  },
  {
    name: "Training",
    url: "/training",
    color: "#022c22",
    logo: BookIcon,
    description: "Do your user training",
    mainMenuNavigable: true,
    routes: [
      {
        title: "Home",
        url: "/training",
        icon: HouseIcon,
        isActive: true,
      },
      {
        title: "Locations",
        icon: EarthIcon,
        isActive: true,
        items: [
          {
            title: "Mainspace",
            icon: HammerIcon,
            url: "/training/locations/mainspace",
          },
          {
            title: "Heartspace",
            icon: ScissorsLineDashedIcon,
            url: "/training/locations/heartspace",
          },
        ],
      },
      {
        title: "Useful Links",
        icon: RssIcon,
        isActive: true,
        items: [
          {
            title: "Approved Materials",
            icon: TrafficConeIcon,
            url: "/training/approved-materials",
          },
          {
            title: "Risk Assessments",
            icon: FileWarningIcon,
            url: "/training/risk-assessments",
          },
        ],
      },
    ],
    navSub: [{ name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon }],
  },
  {
    name: "Printing",
    url: "/printing",
    color: "#1e1b4b",
    logo: PrinterIcon,
    description: "Manage your 3D print jobs (coming soon)",
    mainMenuNavigable: false,
    routes: [
      {
        title: "Home",
        url: "/printing",
        icon: HouseIcon,
        isActive: true,
      },
    ],
    navSub: [{ name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon }],
  },
  {
    name: "Shop",
    url: "/shop",
    color: "#15803d",
    logo: ShoppingBagIcon,
    description: "Browse and order supplies",
    mainMenuNavigable: true,
    routes: [
      {
        title: "Home",
        url: "/shop",
        icon: StoreIcon,
        isActive: true,
      },
      {
        title: "Suppliers",
        url: "/shop/suppliers",
        icon: TruckIcon,
        isActive: true,
      },
      {
        title: "My Orders",
        url: "/shop/orders",
        icon: HistoryIcon,
        isActive: true,
        disabled: true,
      },
      {
        title: "Shopping Cart",
        url: "/shop/cart",
        icon: ShoppingCartIcon,
        isActive: true,
        disabled: true,
      },
    ],
    navSub: [
      { name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon },
      { name: "Return Policy", url: "/shop/return-policy", icon: UndoIcon, disabled: true },
    ],
  },
  {
    name: "User",
    url: "/user",
    logo: UserCogIcon,
    color: "#701a75",
    description: "Manage your user details",
    mainMenuNavigable: true,
    routes: [
      {
        title: "Profile",
        url: "/user",
        icon: UserIcon,
        isActive: true,
      },
       {
        title: "Agreements",
        url: "/user/agreements",
        icon: ClipboardPenIcon,
        isActive: true,
      },
      {
        title: "Settings",
        url: "/user/settings",
        icon: SettingsIcon,
        isActive: false,
      },      {
        title: "Mailing lists",
        url: "/user/mailing-lists",
        icon: MailboxIcon,
        isActive: false,
      },
    ],
    navSub: [{ name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon }],
  },
  {
    name: "Admin",
    url: "/admin",
    color: "#1e1b4b",
    logo: ShieldAlertIcon,
    description: "Administer the iForge",
    mainMenuNavigable: true,
    requiredRoles: ["admin"],
    routes: [
      {
        title: "Dashboard",
        url: "/admin/dashboard",
        icon: LayoutDashboardIcon,
        isActive: true,
      },
      {
        title: "Agreements",
        url: "/admin/agreements",
        icon: FilePenIcon,
        isActive: true,
      },
      {
        title: "Notifications",
        url: "/admin/notifications",
        icon: BellIcon,
        isActive: true,
      },
      {
        title: "Reps",
        url: "/admin/reps",
        icon: ShieldCheckIcon,
        isActive: true,
      },
      {
        title: "Teams",
        url: "/admin/teams",
        icon: UsersIcon,
        isActive: true,
      },
      {
        title: "Users",
        url: "/admin/users",
        icon: BookUserIcon,
        isActive: true,
      },
      {
        title: "Training",
        url: "/admin/training",
        icon: SchoolIcon,
        isActive: true,
      },
      {
        title: "Database",
        url: "/admin/db",
        icon: DatabaseIcon,
        isActive: true,
      },
    ],
    navSub: [{ name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon }],
  },
  {
    name: "Auth",
    url: "/auth",
    color: "#b91c1c",
    logo: FingerprintIcon,
    description: "Authenticate with the iForge",
    mainMenuNavigable: false,
    routes: [],
    navSub: [{ name: "iDocs", url: "https://docs.iforge.sheffield.ac.uk", icon: BookOpenIcon }],
  },
  {
    url: "/",
    name: "Error",
    color: "#b45309",
    logo: ServerCrashIcon,
    description: "Oh no!",
    mainMenuNavigable: false,
    routes: [],
  },
  {
    name: "Socials",
    url: "/socials",
    color: "#fb7185",
    logo: RssIcon,
    description: "iForge social media profiles",
    mainMenuNavigable: false,
    routes: [
      {
        title: "Home",
        url: "/socials",
        icon: HouseIcon,
        isActive: true,
      },
    ],
  },
];
