version: '3.8'

services:
  redis:
    image: redis
    container_name: ignis-redis
    networks:
      - internal
    ports:
      - "6379:6379"

  forge:
    image: forge
    container_name: forge
    networks:
      - internal
    depends_on:
      edgedb:
        condition: service_healthy

  anvil:
    image: anvil
    container_name: anvil
    env_file:
      - .env
    networks:
      - internal
    volumes:
      - ./deploy/certs:/certs
    depends_on:
      edgedb:
        condition: service_healthy

volumes:
  edgedb-data:

networks:
  internal:
    name: internal
    driver: bridge
