[instance]
server-version = "nightly"

[project]
schema-dir = "packages/db"

[hooks]
schema.update.after = "bun regen"

[branch.config]
cors_allow_origins = ["http://localhost:3000",  "http://127.0.0.1:3000",
                      "https://localhost:3000", "https://127.0.0.1:3000"]
