import type { printing } from "@packages/db/interfaces";
export interface PrinterDriver {
  // General interface, inherited by specific printer drivers
  connect(): Promise<void>;
  disconnect(): Promise<void>;
  isConnected(): boolean;

  /*  
    Keeps printers running and status updates, but stops new jobs from being sent
    Can be used for maintenance, manual mode or printer failure
    Can be used with a schedule to allow for maintenace
    */
  disable(): void;
  enable(): void;

  sendJob(job: PrintJob, _timelapse?: boolean): Promise<string>; // If true, records timelapse
  cancelJob(jobId: string): Promise<void>;
  pauseJob(jobId: string): Promise<void>;
  resumeJob(jobId: string): Promise<void>;
  finishJob(id: string): Promise<void>;

  get Config(): PrinterConfig | null;
  get ActiveJob(): PrintJob | null;
  getStatus(fresh?: boolean): Promise<PrinterStatus>; // gets current status;
  subscribeToStatus(callback: (status: PrinterStatus) => void): () => void; // updates status every time interval

  // Live stream done through seperate http server in ignis/apps/Smithy, and routed through forge for auth
  /*
    Workflow is Upload -> Begin print -> Finish print() -> Delete file (locally on printer no db/CDN)
    SendJob does the upload and begin in one
    print?, if able to, allows files to start printing immediately after upload
    */
  uploadFile(file: Buffer, filename: string, print?: boolean): Promise<string>;
  listFiles(): Promise<PrinterFile[]>;
  deleteFile(filename: string): Promise<void>;

  /*
    Allows dynamically updating slot config, only for single slot printers
    When called through API, db updated and queue also updated to reflect changes in frontend as well
    */
  updateSlot(slotId: number, filament: Filament): Promise<void>;

  syncSlots(): Promise<Filament[]>;
}

export interface PrinterConfig {
  ip: string;
  name: string;
  manufacturer: printing.Manafacturers; // Used for driver selection
  filament: Filament[]; // Colour and material, as AMS has various materials and colours in each slot
  queue: printing.QueueType;
  has_camera: boolean;
  [key: string]: any;
}

export interface Filament {
  // For AMS slot config, only 1 used for non AMS printers
  slot_id: number; // 0-based index, for AMS, when extracted from db, the array order defines slots, ie index 0 is slot 1 etc
  material: printing.Material;
  colour: string;
  nozzle_temp_min: number;
  nozzle_temp_max: number;
  bed_temp: number;
}

export interface PrintJob {
  job_id: string; // ID generated by the printer
  uuid: string; // ID from db
  name: string; // Human-readable print name from db, used as the on-printer filename
  gcode_url: string;
  filament: Filament[];
  queue: printing.QueueType;
}

export interface PrinterFile {
  // Return of listFiles(), files stored on printers
  filename: string;
  size: number;
  uploaded_at: Date;
}

export interface PrinterStatus {
  state: "idle" | "printing" | "paused" | "finished" | "disconnected" | "disabled" | "error";
  current_job?: {
    print_job: PrintJob;
    name: string;
    progress: number;
    time_remaining: number;
  };
  temperature?: {
    nozzle: {
      current: number;
      target: number;
    };
    bed: {
      current: number;
      target: number;
    };
  };
  errors?: string[];
}
