// GENERATED by @gel/generate v0.7.1
// This file is automatically generated from .edgeql query files.
// To make changes, edit the source .edgeql file and regenerate.

export * as gel from "gel";
export { spec } from "./__spec__";
export * as syntax from "./syntax";
export * as castMaps from "./castMaps";
