// GENERATED by @gel/generate v0.6.2

export * from "./external";
export { createClient } from "gel";
import * as $ from "./reflection";
import * as $syntax from "./syntax";
import * as $op from "./operators";
import _std from "./modules/std";
import _cfg from "./modules/cfg";
import _event from "./modules/event";
import _ext from "./modules/ext";
import _notification from "./modules/notification";
import _schema from "./modules/schema";
import _sign_in from "./modules/sign_in";
import _sys from "./modules/sys";
import _training from "./modules/training";
import _users from "./modules/users";
import _ai_rep from "./modules/ai_rep";
import _default from "./modules/default";
import _team from "./modules/team";

const ExportDefault: typeof _std & 
  typeof _default & 
  $.util.OmitDollarPrefixed<typeof $syntax> & 
  typeof $op & {
  "std": typeof _std;
  "cfg": typeof _cfg;
  "event": typeof _event;
  "ext": typeof _ext;
  "notification": typeof _notification;
  "schema": typeof _schema;
  "sign_in": typeof _sign_in;
  "sys": typeof _sys;
  "training": typeof _training;
  "users": typeof _users;
  "ai_rep": typeof _ai_rep;
  "default": typeof _default;
  "team": typeof _team;
} = {
  ..._std,
  ..._default,
  ...$.util.omitDollarPrefixed($syntax),
  ...$op,
  "std": _std,
  "cfg": _cfg,
  "event": _event,
  "ext": _ext,
  "notification": _notification,
  "schema": _schema,
  "sign_in": _sign_in,
  "sys": _sys,
  "training": _training,
  "users": _users,
  "ai_rep": _ai_rep,
  "default": _default,
  "team": _team,
};
const Cardinality = $.Cardinality;
type Cardinality = $.Cardinality;
export type Set<
  Type extends $.BaseType,
  Card extends $.Cardinality = $.Cardinality.Many
> = $.TypeSet<Type, Card>;


export default ExportDefault;
export { Cardinality };
