// GENERATED by @gel/generate v0.7.1
// This file is automatically generated from .edgeql query files.
// To make changes, edit the source .edgeql file and regenerate.

import type { TypeSet, setToTsType } from "./typesystem";

export * from "./literal";
export * from "./path";
export * from "./set";
export * from "./cast";
export * from "./select";
export * from "./update";
export * from "./insert";
export * from "./group";
export * from "./collections";
export * from "./funcops";
export * from "./for";
export * from "./with";
export * from "./params";
export * from "./globals";
export * from "./detached";
export * from "./toEdgeQL";
export * from "./range";

export type $infer<A extends TypeSet> = setToTsType<A>;
