// GENERATED by @gel/generate v0.7.1
// This file is automatically generated from .edgeql query files.
// To make changes, edit the source .edgeql file and regenerate.

import type {Executor} from "gel";

export type AddInPersonTrainingArgs = {
  readonly "created_at": Date;
  readonly "id": string;
  readonly "rep_id": string;
  readonly "training_id": string;
};

export type AddInPersonTrainingReturns = {
  "id": string;
};

export function addInPersonTraining(client: Executor, args: AddInPersonTrainingArgs): Promise<AddInPersonTrainingReturns> {
  return client.queryRequiredSingle(`\
with
    rep := <users::Rep><uuid>$rep_id,
    user := <users::User><uuid>$id,
update user
set {
    training += (
        select .training {
            @created_at := @created_at,
            @infraction := @infraction,
            @in_person_created_at := <datetime>$created_at,
            @in_person_signed_off_by := rep.id,
        } filter .id =  <uuid>$training_id
    )
}`, args);

}
