// GENERATED by @gel/generate v0.6.2

import type {Executor} from "gel";

export type GetSignInToolsArgs = {
  readonly "id": string;
  readonly "name": ("MAINSPACE" | "HEARTSPACE");
  readonly "collapse"?: boolean | null;
};

export type GetSignInToolsReturns = Array<{
  "compulsory": boolean;
  "id": string;
  "name": string;
  "description": Array<string>;
  "selectable": Array<("DO_ONLINE" | "REVOKED" | "EXPIRED" | "DO_IN_PERSON" | "NONE_REMAINING" | "DO_IN_PERSON_OR_REP_ONLINE" | "DO_REP_ONLINE" | "DO_IN_PERSON_OR_REP_IN_PERSON" | "DO_REP_IN_PERSON" | "REPS_UNTRAINED" | "TOOL_BROKEN" | "NONE")>;
}>;

export function getSignInTools(client: Executor, args: GetSignInToolsArgs): Promise<GetSignInToolsReturns> {
  return client.query(`\
with
    location := (
        select assert_exists(sign_in::Location filter .name = <sign_in::LocationName>$name)
    ),
    user := assert_exists(<users::User><uuid>$id),
    tools := (select tools::Tool filter location = .location and not .grouped),
    groups := (select tools::GroupedTool filter location = .location)
select (tools union groups) {
    id,
    name,
    description := [is tools::Tool].description ?? [is tools::GroupedTool].tools.description,
    compulsory := any(.training.compulsory),
    selectable := (
      with
        next_step := training::get_status(.training, user, collapse := <optional bool>$collapse).next_step
      select {
        # TODO in future not booked
        tools::Selectability.NONE_REMAINING if [is tools::Tool].quantity = 0 else <tools::Selectability>{},  # inventoried tools cannot be grouped
        if [is tools::Tool] is tools::Tool then  # cursed ass logic
          if [is tools::Tool].status.code = tools::Status.OUT_OF_ORDER then
            tools::Selectability.TOOL_BROKEN
          else
            <tools::Selectability>{}
        else
          if all([is tools::GroupedTool].tools.status.code = tools::Status.OUT_OF_ORDER) then
            tools::Selectability.TOOL_BROKEN
          else
            <tools::Selectability>{},
        <tools::Selectability><str>next_step if next_step != training::NextStep.NONE else <tools::Selectability>{},
        # if they're a rep they can sign in to use the machines they want even if the reps aren't trained
        if .training not in location.supervisable_training and user is not users::Rep then
          tools::Selectability.REPS_UNTRAINED
        else
          <tools::Selectability>{},
    })
}`, args);

}
