// GENERATED by @gel/generate v0.7.1
// This file is automatically generated from .edgeql query files.
// To make changes, edit the source .edgeql file and regenerate.

import type {RelativeDuration, Duration, Executor} from "gel";

export type GetTrainingForEditingArgs = {
  readonly "id": string;
};

export type GetTrainingForEditingReturns = {
  "compulsory": boolean;
  "created_at": Date;
  "description": string;
  "enabled": boolean;
  "expires_after": RelativeDuration;
  "id": string;
  "in_person": boolean;
  "name": string;
  "updated_at": Date;
  "icon_url": string | null;
  "training_lockout": Duration | null;
  "locations": Array<("MAINSPACE" | "HEARTSPACE" | "GEORGE_PORTER")>;
  "pages": Array<{
    "content": string;
    "enabled": boolean;
    "id": string;
    "index": number;
    "name": string;
    "duration": Duration | null;
  }>;
  "questions": Array<{
    "content": string;
    "enabled": boolean;
    "id": string;
    "index": number;
    "type": ("SINGLE" | "MULTI");
  }>;
  "sections": Array<{
    "content": string;
    "enabled": boolean;
    "id": string;
    "index": number;
    "type_name": string;
    "duration": Duration | null;
    "name": string | null;
    "answers": Array<{
      "content": string;
      "id": string;
      "description": string | null;
    }>;
  }>;
  "rep": {
    "compulsory": boolean;
    "created_at": Date;
    "description": string;
    "enabled": boolean;
    "expires_after": RelativeDuration;
    "id": string;
    "in_person": boolean;
    "name": string;
    "updated_at": Date;
    "icon_url": string | null;
    "training_lockout": Duration | null;
    "locations": Array<("MAINSPACE" | "HEARTSPACE" | "GEORGE_PORTER")>;
  } | null;
};

export function getTrainingForEditing(client: Executor, args: GetTrainingForEditingArgs): Promise<GetTrainingForEditingReturns> {
  return client.queryRequiredSingle(`\
with training := <training::Training><uuid>$id,
select training {
    **,
    sections: {
        *,
        type_name := .__type__.name,
        [is training::TrainingPage].name,
        [is training::TrainingPage].duration,
        [is training::Question].answers: {
            id,
            content,
            description,
        },
    }
}`, args);

}
