// GENERATED by @gel/generate v0.7.1
// This file is automatically generated from .edgeql query files.
// To make changes, edit the source .edgeql file and regenerate.

import type {Executor} from "gel";

export type SearchMailingListsArgs = {
  readonly "limit": number;
  readonly "query": string;
};

export type SearchMailingListsReturns = Array<{
  "id": string;
  "name": string;
  "score": number;
}>;

export function searchMailingLists(client: Executor, args: SearchMailingListsArgs): Promise<SearchMailingListsReturns> {
  return client.query(`\
with res := (
  select fts::search(notification::MailingList, <str>$query, language := 'eng')
)
select res.object {
    id,
    name,
    score := res.score,
}
order by res.score desc
limit <int16>$limit;`, args);

}
