// GENERATED by @gel/generate v0.6.2

import type {Executor} from "gel";

export type SearchEventsArgs = {
  readonly "query": string;
  readonly "limit": number;
};

export type SearchEventsReturns = Array<{
  "id": string;
  "name": string;
  "score": number;
}>;

export function searchEvents(client: Executor, args: SearchEventsArgs): Promise<SearchEventsReturns> {
  return client.query(`\
with res := (
  select fts::search(event::Event, <str>$query, language := 'eng')
)
select res.object {
    id,
    name,
    score := res.score,
}
order by res.score desc
limit <int16>$limit;`, args);

}
