// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _users from "./users";
import type * as _stdnethttp from "./std/net/http";
export type $current_user_role_names = $.ScalarType<"std::str", string>;
const current_user_role_names: $.scalarTypeWithConstructor<_std.$str, never> = $.makeType<$.scalarTypeWithConstructor<_std.$str, never>>(_.spec, "e841099c-3c38-11f1-9aba-5932ed7b3493", _.syntax.literal);

export type $is_admin = $.ScalarType<"std::bool", boolean>;
const is_admin: $.scalarTypeWithConstructor<_std.$bool, never> = $.makeType<$.scalarTypeWithConstructor<_std.$bool, never>>(_.spec, "e95709b2-3c38-11f1-a343-7dd9d232be78", _.syntax.literal);

export type $is_desk_or_higher = $.ScalarType<"std::bool", boolean>;
const is_desk_or_higher: $.scalarTypeWithConstructor<_std.$bool, never> = $.makeType<$.scalarTypeWithConstructor<_std.$bool, never>>(_.spec, "e84fa8da-3c38-11f1-9f19-0902f0a8c3f8", _.syntax.literal);

export type $is_rep_or_higher = $.ScalarType<"std::bool", boolean>;
const is_rep_or_higher: $.scalarTypeWithConstructor<_std.$bool, never> = $.makeType<$.scalarTypeWithConstructor<_std.$bool, never>>(_.spec, "eb030734-3c38-11f1-bea0-6919ba4cacbd", _.syntax.literal);

export type $CreatedAtλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "created_at": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, true, true>;
}>;
type $CreatedAt = $.ObjectType<"default::CreatedAt", $CreatedAtλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "users::User" | "default::user" | "event::Event" | "notification::Notification" | "notification::AuthoredNotification" | "notification::MailingList" | "notification::SystemNotification" | "printing::PrintAuditEntry" | "printing::PrintHistory" | "printing::PrinterAuditEntry" | "shop::Purchase" | "shop::Skew" | "sign_in::Agreement" | "sign_in::Location" | "sign_in::QueuePlace" | "sign_in::Reason" | "sign_in::SignIn" | "sign_in::UserRegistration" | "tools::Booking" | "training::Session" | "training::Training" | "users::Infraction" | "users::Integration" | "users::Rep">;
const $CreatedAt = $.makeType<$CreatedAt>(_.spec, "e4bdd210-3c37-11f1-a20b-6f99b82663cc", _.syntax.literal);

const CreatedAt: $.$expr_PathNode<$.TypeSet<$CreatedAt, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CreatedAt, $.Cardinality.Many), null);

export type $AuditableλShape = $.typeutil.flatten<$CreatedAtλShape & {
  "updated_at": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
}>;
type $Auditable = $.ObjectType<"default::Auditable", $AuditableλShape, null, [
  ...$CreatedAt['__exclusives__'],
], "users::User" | "default::user" | "notification::Notification" | "notification::AuthoredNotification" | "notification::MailingList" | "notification::SystemNotification" | "shop::Purchase" | "shop::Skew" | "sign_in::Agreement" | "sign_in::Location" | "sign_in::Reason" | "tools::Booking" | "training::Session" | "training::Training" | "users::Integration" | "users::Rep">;
const $Auditable = $.makeType<$Auditable>(_.spec, "e4bf6440-3c37-11f1-8a3f-752f326103e6", _.syntax.literal);

const Auditable: $.$expr_PathNode<$.TypeSet<$Auditable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Auditable, $.Cardinality.Many), null);

export type $BaseListenable_37391b3a3c3811f1a20f194c51c168d1λShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
}>;
type $BaseListenable_37391b3a3c3811f1a20f194c51c168d1 = $.ObjectType<"default::_BaseListenable", $BaseListenable_37391b3a3c3811f1a20f194c51c168d1λShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "users::User" | "default::user" | "sign_in::Agreement" | "sign_in::Location" | "sign_in::QueuePlace" | "sign_in::Reason" | "sign_in::SignIn" | "users::Rep">;
const $BaseListenable_37391b3a3c3811f1a20f194c51c168d1 = $.makeType<$BaseListenable_37391b3a3c3811f1a20f194c51c168d1>(_.spec, "37391b3a-3c38-11f1-a20f-194c51c168d1", _.syntax.literal);

const BaseListenable_37391b3a3c3811f1a20f194c51c168d1: $.$expr_PathNode<$.TypeSet<$BaseListenable_37391b3a3c3811f1a20f194c51c168d1, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($BaseListenable_37391b3a3c3811f1a20f194c51c168d1, $.Cardinality.Many), null);

export type $ListenableλShape = $.typeutil.flatten<$BaseListenable_37391b3a3c3811f1a20f194c51c168d1λShape & {
}>;
type $Listenable = $.ObjectType<"default::Listenable", $ListenableλShape, null, [
  ...$BaseListenable_37391b3a3c3811f1a20f194c51c168d1['__exclusives__'],
], "users::User" | "default::user" | "sign_in::QueuePlace" | "sign_in::Reason" | "sign_in::SignIn" | "users::Rep">;
const $Listenable = $.makeType<$Listenable>(_.spec, "375e3b36-3c38-11f1-9170-2ddf08b4d672", _.syntax.literal);

const Listenable: $.$expr_PathNode<$.TypeSet<$Listenable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Listenable, $.Cardinality.Many), null);

export type $ListenableWithChangesλShape = $.typeutil.flatten<$BaseListenable_37391b3a3c3811f1a20f194c51c168d1λShape & {
}>;
type $ListenableWithChanges = $.ObjectType<"default::ListenableWithChanges", $ListenableWithChangesλShape, null, [
  ...$BaseListenable_37391b3a3c3811f1a20f194c51c168d1['__exclusives__'],
], "sign_in::Agreement" | "sign_in::Location">;
const $ListenableWithChanges = $.makeType<$ListenableWithChanges>(_.spec, "37a68ea4-3c38-11f1-8ce4-5571fd576a52", _.syntax.literal);

const ListenableWithChanges: $.$expr_PathNode<$.TypeSet<$ListenableWithChanges, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($ListenableWithChanges, $.Cardinality.Many), null);

export type $TimedλShape = $.typeutil.flatten<$CreatedAtλShape & {
  "ends_at": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "duration": $.PropertyDesc<_std.$duration, $.Cardinality.One, false, true, false, false>;
}>;
type $Timed = $.ObjectType<"default::Timed", $TimedλShape, null, [
  ...$CreatedAt['__exclusives__'],
], "sign_in::SignIn">;
const $Timed = $.makeType<$Timed>(_.spec, "e57551ec-3c37-11f1-8d9e-c594ff381f73", _.syntax.literal);

const Timed: $.$expr_PathNode<$.TypeSet<$Timed, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Timed, $.Cardinality.Many), null);

export type $userλShape = $.typeutil.flatten<_users.$UserλShape & {
}>;
type $user = $.ObjectType<"default::user", $userλShape, null, [
  ..._users.$User['__exclusives__'],
], "default::user">;
const $user = $.makeType<$user>(_.spec, "e4db7f54-3c37-11f1-bbac-09b94092963b", _.syntax.literal);

const user: $.$expr_PathNode<$.TypeSet<$user, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($user, $.Cardinality.Many), null);

type binλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
> = $.$expr_Function<
  _std.$number, $.cardutil.paramCardinality<P1>
>;
function bin<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$str>>,
>(
  string: P1,
): binλFuncExpr<P1>;
function bin(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('default::bin', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-000000000101", optional: false, setoftype: false, variadic: false}], returnTypeId: "00000000-0000-0000-0000-0000000001ff"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "default::bin",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type notify_webhookλFuncExpr<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$json>>,
> = $.$expr_Function<
  _stdnethttp.$ScheduledRequest, $.cardutil.paramCardinality<P1>
>;
function notify_webhook<
  P1 extends _.castMaps.orScalarLiteral<$.TypeSet<_std.$json>>,
>(
  body: P1,
): notify_webhookλFuncExpr<P1>;
function notify_webhook(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('default::notify_webhook', args, _.spec, [
    {args: [{typeId: "00000000-0000-0000-0000-00000000010f", optional: false, setoftype: false, variadic: false}], returnTypeId: "e6bf05a7-60c7-51dd-b30d-c8fce5bcadfd"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "default::notify_webhook",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

const $default__globals: {  CDN_URL: _.syntax.$expr_Global<
              // "default::CDN_URL",
              _std.$str,
              $.Cardinality.AtMostOne
              >,  INFRACTIONS_WEBHOOK_URL: _.syntax.$expr_Global<
              // "default::INFRACTIONS_WEBHOOK_URL",
              _std.$str,
              $.Cardinality.AtMostOne
              >,  PUB_SUB_SECRET: _.syntax.$expr_Global<
              // "default::PUB_SUB_SECRET",
              _std.$str,
              $.Cardinality.AtMostOne
              >,  current_user_role_names: _.syntax.$expr_Global<
              // "default::current_user_role_names",
              $current_user_role_names,
              $.Cardinality.Many
              >,  is_admin: _.syntax.$expr_Global<
              // "default::is_admin",
              $is_admin,
              $.Cardinality.One
              >,  is_desk_or_higher: _.syntax.$expr_Global<
              // "default::is_desk_or_higher",
              $is_desk_or_higher,
              $.Cardinality.One
              >,  is_rep_or_higher: _.syntax.$expr_Global<
              // "default::is_rep_or_higher",
              $is_rep_or_higher,
              $.Cardinality.One
              >,  user: _.syntax.$expr_Global<
              // "default::user",
              $user,
              $.Cardinality.AtMostOne
              >} = {  CDN_URL: _.syntax.makeGlobal(
              "default::CDN_URL",
              $.makeType(_.spec, "00000000-0000-0000-0000-000000000101", _.syntax.literal),
              $.Cardinality.AtMostOne) as any,  INFRACTIONS_WEBHOOK_URL: _.syntax.makeGlobal(
              "default::INFRACTIONS_WEBHOOK_URL",
              $.makeType(_.spec, "00000000-0000-0000-0000-000000000101", _.syntax.literal),
              $.Cardinality.AtMostOne) as any,  PUB_SUB_SECRET: _.syntax.makeGlobal(
              "default::PUB_SUB_SECRET",
              $.makeType(_.spec, "00000000-0000-0000-0000-000000000101", _.syntax.literal),
              $.Cardinality.AtMostOne) as any,  current_user_role_names: _.syntax.makeGlobal(
              "default::current_user_role_names",
              $.makeType(_.spec, "e841099c-3c38-11f1-9aba-5932ed7b3493", _.syntax.literal),
              $.Cardinality.Many) as any,  is_admin: _.syntax.makeGlobal(
              "default::is_admin",
              $.makeType(_.spec, "e95709b2-3c38-11f1-a343-7dd9d232be78", _.syntax.literal),
              $.Cardinality.One) as any,  is_desk_or_higher: _.syntax.makeGlobal(
              "default::is_desk_or_higher",
              $.makeType(_.spec, "e84fa8da-3c38-11f1-9f19-0902f0a8c3f8", _.syntax.literal),
              $.Cardinality.One) as any,  is_rep_or_higher: _.syntax.makeGlobal(
              "default::is_rep_or_higher",
              $.makeType(_.spec, "eb030734-3c38-11f1-bea0-6919ba4cacbd", _.syntax.literal),
              $.Cardinality.One) as any,  user: _.syntax.makeGlobal(
              "default::user",
              $.makeType(_.spec, "e4db7f54-3c37-11f1-bbac-09b94092963b", _.syntax.literal),
              $.Cardinality.AtMostOne) as any};



export { current_user_role_names, is_admin, is_desk_or_higher, is_rep_or_higher, $CreatedAt, CreatedAt, $Auditable, Auditable, $BaseListenable_37391b3a3c3811f1a20f194c51c168d1, BaseListenable_37391b3a3c3811f1a20f194c51c168d1, $Listenable, Listenable, $ListenableWithChanges, ListenableWithChanges, $Timed, Timed, $user, user };

type __defaultExports = {
  "current_user_role_names": typeof current_user_role_names;
  "is_admin": typeof is_admin;
  "is_desk_or_higher": typeof is_desk_or_higher;
  "is_rep_or_higher": typeof is_rep_or_higher;
  "CreatedAt": typeof CreatedAt;
  "Auditable": typeof Auditable;
  "_BaseListenable": typeof BaseListenable_37391b3a3c3811f1a20f194c51c168d1;
  "Listenable": typeof Listenable;
  "ListenableWithChanges": typeof ListenableWithChanges;
  "Timed": typeof Timed;
  "user": typeof user;
  "bin": typeof bin;
  "notify_webhook": typeof notify_webhook;
  "global": typeof $default__globals
};
const __defaultExports: __defaultExports = {
  "current_user_role_names": current_user_role_names,
  "is_admin": is_admin,
  "is_desk_or_higher": is_desk_or_higher,
  "is_rep_or_higher": is_rep_or_higher,
  "CreatedAt": CreatedAt,
  "Auditable": Auditable,
  "_BaseListenable": BaseListenable_37391b3a3c3811f1a20f194c51c168d1,
  "Listenable": Listenable,
  "ListenableWithChanges": ListenableWithChanges,
  "Timed": Timed,
  "user": user,
  "bin": bin,
  "notify_webhook": notify_webhook,
  "global": $default__globals
};
export default __defaultExports;
