// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _schema from "./schema";
import type * as _shop from "./shop";
export type $DimensionλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "fields": $.LinkDesc<_schema.$Pointer, $.Cardinality.AtLeastOne, {}, false, true,  false, false>;
  "<_dimensions[is shop::Skew]": $.LinkDesc<_shop.$Skew, $.Cardinality.Many, {}, false, false,  false, false>;
  "<_dimensions": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Dimension = $.ObjectType<"dimensions::Dimension", $DimensionλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "dimensions::Cuboid" | "dimensions::Cylindrical" | "dimensions::ISO216" | "dimensions::LiquidVolume" | "dimensions::Mass" | "dimensions::Thread">;
const $Dimension = $.makeType<$Dimension>(_.spec, "645ecf06-3c38-11f1-901e-9525badcb66a", _.syntax.literal);

const Dimension: $.$expr_PathNode<$.TypeSet<$Dimension, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Dimension, $.Cardinality.Many), null);

export type $CuboidλShape = $.typeutil.flatten<$DimensionλShape & {
  "height": $.PropertyDesc<_std.$float64, $.Cardinality.One, false, false, false, false>;
  "length": $.PropertyDesc<_std.$float64, $.Cardinality.One, false, false, false, false>;
  "unit": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "width": $.PropertyDesc<_std.$float64, $.Cardinality.One, false, false, false, false>;
  "formatted": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
}>;
type $Cuboid = $.ObjectType<"dimensions::Cuboid", $CuboidλShape, null, [
  ...$Dimension['__exclusives__'],
], "dimensions::Cuboid">;
const $Cuboid = $.makeType<$Cuboid>(_.spec, "64628984-3c38-11f1-ba1e-07b9f1d25ed6", _.syntax.literal);

const Cuboid: $.$expr_PathNode<$.TypeSet<$Cuboid, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Cuboid, $.Cardinality.Many), null);

export type $CylindricalλShape = $.typeutil.flatten<$DimensionλShape & {
  "diameter": $.PropertyDesc<_std.$float64, $.Cardinality.One, false, false, false, false>;
  "length": $.PropertyDesc<_std.$float64, $.Cardinality.One, false, false, false, false>;
  "unit": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "formatted": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
}>;
type $Cylindrical = $.ObjectType<"dimensions::Cylindrical", $CylindricalλShape, null, [
  ...$Dimension['__exclusives__'],
], "dimensions::Cylindrical">;
const $Cylindrical = $.makeType<$Cylindrical>(_.spec, "6467a6d0-3c38-11f1-9be8-9f3830b8e6e4", _.syntax.literal);

const Cylindrical: $.$expr_PathNode<$.TypeSet<$Cylindrical, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Cylindrical, $.Cardinality.Many), null);

export type $ISO216λShape = $.typeutil.flatten<$DimensionλShape & {
  "size": $.PropertyDesc<_std.$int16, $.Cardinality.One, false, false, false, false>;
  "thickness": $.PropertyDesc<_std.$float64, $.Cardinality.AtMostOne, false, false, false, false>;
  "unit": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "formatted": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
}>;
type $ISO216 = $.ObjectType<"dimensions::ISO216", $ISO216λShape, null, [
  ...$Dimension['__exclusives__'],
], "dimensions::ISO216">;
const $ISO216 = $.makeType<$ISO216>(_.spec, "646c5c3e-3c38-11f1-96a9-05f4e1355904", _.syntax.literal);

const ISO216: $.$expr_PathNode<$.TypeSet<$ISO216, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($ISO216, $.Cardinality.Many), null);

export type $LiquidVolumeλShape = $.typeutil.flatten<$DimensionλShape & {
  "unit": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "volume": $.PropertyDesc<_std.$float64, $.Cardinality.One, false, false, false, false>;
  "formatted": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
}>;
type $LiquidVolume = $.ObjectType<"dimensions::LiquidVolume", $LiquidVolumeλShape, null, [
  ...$Dimension['__exclusives__'],
], "dimensions::LiquidVolume">;
const $LiquidVolume = $.makeType<$LiquidVolume>(_.spec, "64722740-3c38-11f1-970c-670671ce0ac8", _.syntax.literal);

const LiquidVolume: $.$expr_PathNode<$.TypeSet<$LiquidVolume, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($LiquidVolume, $.Cardinality.Many), null);

export type $MassλShape = $.typeutil.flatten<$DimensionλShape & {
  "mass": $.PropertyDesc<_std.$float64, $.Cardinality.One, false, false, false, false>;
  "unit": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "formatted": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
}>;
type $Mass = $.ObjectType<"dimensions::Mass", $MassλShape, null, [
  ...$Dimension['__exclusives__'],
], "dimensions::Mass">;
const $Mass = $.makeType<$Mass>(_.spec, "6476a7a2-3c38-11f1-a1c2-772721b07af2", _.syntax.literal);

const Mass: $.$expr_PathNode<$.TypeSet<$Mass, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Mass, $.Cardinality.Many), null);

export type $ThreadλShape = $.typeutil.flatten<$DimensionλShape & {
  "diameter": $.PropertyDesc<_std.$float64, $.Cardinality.One, false, false, false, false>;
  "length": $.PropertyDesc<_std.$float64, $.Cardinality.One, false, false, false, false>;
  "unit": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "formatted": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
}>;
type $Thread = $.ObjectType<"dimensions::Thread", $ThreadλShape, null, [
  ...$Dimension['__exclusives__'],
], "dimensions::Thread">;
const $Thread = $.makeType<$Thread>(_.spec, "647b0874-3c38-11f1-af21-055b55280ee8", _.syntax.literal);

const Thread: $.$expr_PathNode<$.TypeSet<$Thread, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Thread, $.Cardinality.Many), null);



export { $Dimension, Dimension, $Cuboid, Cuboid, $Cylindrical, Cylindrical, $ISO216, ISO216, $LiquidVolume, LiquidVolume, $Mass, Mass, $Thread, Thread };

type __defaultExports = {
  "Dimension": typeof Dimension;
  "Cuboid": typeof Cuboid;
  "Cylindrical": typeof Cylindrical;
  "ISO216": typeof ISO216;
  "LiquidVolume": typeof LiquidVolume;
  "Mass": typeof Mass;
  "Thread": typeof Thread
};
const __defaultExports: __defaultExports = {
  "Dimension": Dimension,
  "Cuboid": Cuboid,
  "Cylindrical": Cylindrical,
  "ISO216": ISO216,
  "LiquidVolume": LiquidVolume,
  "Mass": Mass,
  "Thread": Thread
};
export default __defaultExports;
