// GENERATED by @gel/generate v0.7.1
// This file is automatically generated from .edgeql query files.
// To make changes, edit the source .edgeql file and regenerate.

import * as $ from "../reflection";
import * as _ from "../imports";
import _module__ai from "./ext/ai";
import _module__auth from "./ext/auth";
import _module__pgvector from "./ext/pgvector";
import _module__pg_trgm from "./ext/pg_trgm";
import _module__pgcrypto from "./ext/pgcrypto";


type __defaultExports = {
  "ai": typeof _module__ai;
  "auth": typeof _module__auth;
  "pgvector": typeof _module__pgvector;
  "pg_trgm": typeof _module__pg_trgm;
  "pgcrypto": typeof _module__pgcrypto
};
const __defaultExports: __defaultExports = {
  "ai": _module__ai,
  "auth": _module__auth,
  "pgvector": _module__pgvector,
  "pg_trgm": _module__pg_trgm,
  "pgcrypto": _module__pgcrypto
};
export default __defaultExports;
