// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _default from "./default";
import type * as _users from "./users";
import type * as _team from "./team";
import type * as _event from "./event";
export type $DeliveryMethod = {
  "BANNER": $.$expr_Literal<$DeliveryMethod>;
  "EMAIL": $.$expr_Literal<$DeliveryMethod>;
  "TRAY": $.$expr_Literal<$DeliveryMethod>;
  "POPUP": $.$expr_Literal<$DeliveryMethod>;
  "DISCORD": $.$expr_Literal<$DeliveryMethod>;
} & $.EnumType<"notification::DeliveryMethod", ["BANNER", "EMAIL", "TRAY", "POPUP", "DISCORD"]>;
const DeliveryMethod: $DeliveryMethod = $.makeType<$DeliveryMethod>(_.spec, "df16dd36-b9ed-11f0-9638-21f3e831f1c8", _.syntax.literal);

export type $Status = {
  "DRAFT": $.$expr_Literal<$Status>;
  "REVIEW": $.$expr_Literal<$Status>;
  "QUEUED": $.$expr_Literal<$Status>;
  "SENDING": $.$expr_Literal<$Status>;
  "SENT": $.$expr_Literal<$Status>;
  "ERRORED": $.$expr_Literal<$Status>;
} & $.EnumType<"notification::Status", ["DRAFT", "REVIEW", "QUEUED", "SENDING", "SENT", "ERRORED"]>;
const Status: $Status = $.makeType<$Status>(_.spec, "df16fa5a-b9ed-11f0-b93d-913c5e25b857", _.syntax.literal);

export type $Type = {
  "ADMIN": $.$expr_Literal<$Type>;
  "ADVERT": $.$expr_Literal<$Type>;
  "ANNOUNCEMENT": $.$expr_Literal<$Type>;
  "EVENT": $.$expr_Literal<$Type>;
  "HEALTH_AND_SAFETY": $.$expr_Literal<$Type>;
  "INFRACTION": $.$expr_Literal<$Type>;
  "PRINTING": $.$expr_Literal<$Type>;
  "QUEUE_SLOT_ACTIVE": $.$expr_Literal<$Type>;
  "RECRUITMENT": $.$expr_Literal<$Type>;
  "REFERRAL": $.$expr_Literal<$Type>;
  "REMINDER": $.$expr_Literal<$Type>;
  "TRAINING": $.$expr_Literal<$Type>;
} & $.EnumType<"notification::Type", ["ADMIN", "ADVERT", "ANNOUNCEMENT", "EVENT", "HEALTH_AND_SAFETY", "INFRACTION", "PRINTING", "QUEUE_SLOT_ACTIVE", "RECRUITMENT", "REFERRAL", "REMINDER", "TRAINING"]>;
const Type: $Type = $.makeType<$Type>(_.spec, "df17092a-b9ed-11f0-9028-2dfb8b398e14", _.syntax.literal);

export type $AllRepsλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "MAGIC": $.PropertyDesc<_std.$int16, $.Cardinality.One, true, false, true, true>;
}>;
type $AllReps = $.ObjectType<"notification::AllReps", $AllRepsλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {MAGIC: {__element__: _std.$int16, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "notification::AllReps">;
const $AllReps = $.makeType<$AllReps>(_.spec, "def81bcc-b9ed-11f0-b41c-f754699ab751", _.syntax.literal);

const AllReps: $.$expr_PathNode<$.TypeSet<$AllReps, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($AllReps, $.Cardinality.Many), null);

export type $AllUsersλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "MAGIC": $.PropertyDesc<_std.$int16, $.Cardinality.One, true, false, true, true>;
}>;
type $AllUsers = $.ObjectType<"notification::AllUsers", $AllUsersλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {MAGIC: {__element__: _std.$int16, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "notification::AllUsers">;
const $AllUsers = $.makeType<$AllUsers>(_.spec, "17cd75e2-b9ee-11f0-8792-758a8c74bfc0", _.syntax.literal);

const AllUsers: $.$expr_PathNode<$.TypeSet<$AllUsers, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($AllUsers, $.Cardinality.Many), null);

export type $NotificationλShape = $.typeutil.flatten<_default.$AuditableλShape & {
  "content": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "status": $.PropertyDesc<$Status, $.Cardinality.One, false, false, false, false>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "type": $.PropertyDesc<$Type, $.Cardinality.One, false, false, false, false>;
  "targets": $.LinkDesc<_users.$User | _team.$Team | _event.$Event | $AllReps | $MailingList | $AllUsers, $.Cardinality.AtLeastOne, {}, false, false,  false, false>;
  "delivery_methods": $.PropertyDesc<$DeliveryMethod, $.Cardinality.AtLeastOne, false, false, false, false>;
  "dispatched_at": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "priority": $.PropertyDesc<_std.$int16, $.Cardinality.One, false, false, false, true>;
  "<notifications[is users::User]": $.LinkDesc<_users.$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<notifications[is users::Rep]": $.LinkDesc<_users.$Rep, $.Cardinality.Many, {}, false, false,  false, false>;
  "<notifications[is user]": $.LinkDesc<_default.$user, $.Cardinality.Many, {}, false, false,  false, false>;
  "<notifications": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Notification = $.ObjectType<"notification::Notification", $NotificationλShape, null, [
  ..._default.$Auditable['__exclusives__'],
], "notification::Notification" | "notification::AuthoredNotification" | "notification::SystemNotification">;
const $Notification = $.makeType<$Notification>(_.spec, "e4646e20-b9ed-11f0-86d7-cbab95b3788e", _.syntax.literal);

const Notification: $.$expr_PathNode<$.TypeSet<$Notification, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Notification, $.Cardinality.Many), null);

export type $AuthoredNotificationλShape = $.typeutil.flatten<$NotificationλShape & {
  "approved_by": $.LinkDesc<_users.$Rep, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "author": $.LinkDesc<_users.$User, $.Cardinality.One, {}, false, false,  false, false>;
  "approved_on": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $AuthoredNotification = $.ObjectType<"notification::AuthoredNotification", $AuthoredNotificationλShape, null, [
  ...$Notification['__exclusives__'],
], "notification::AuthoredNotification">;
const $AuthoredNotification = $.makeType<$AuthoredNotification>(_.spec, "e466774b-b9ed-11f0-b493-67ae88ae9ec2", _.syntax.literal);

const AuthoredNotification: $.$expr_PathNode<$.TypeSet<$AuthoredNotification, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($AuthoredNotification, $.Cardinality.Many), null);

export type $MailingListλShape = $.typeutil.flatten<_default.$AuditableλShape & {
  "description": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "subscribers": $.LinkDesc<_users.$User, $.Cardinality.Many, {}, false, true,  false, false>;
  "<mailing_list_subscriptions[is users::User]": $.LinkDesc<_users.$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<mailing_list_subscriptions[is users::Rep]": $.LinkDesc<_users.$Rep, $.Cardinality.Many, {}, false, false,  false, false>;
  "<mailing_list_subscriptions[is user]": $.LinkDesc<_default.$user, $.Cardinality.Many, {}, false, false,  false, false>;
  "<mailing_list_subscriptions": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $MailingList = $.ObjectType<"notification::MailingList", $MailingListλShape, null, [
  ..._default.$Auditable['__exclusives__'],
], "notification::MailingList">;
const $MailingList = $.makeType<$MailingList>(_.spec, "e468b828-b9ed-11f0-9316-5907731045dc", _.syntax.literal);

const MailingList: $.$expr_PathNode<$.TypeSet<$MailingList, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($MailingList, $.Cardinality.Many), null);

export type $SystemNotificationλShape = $.typeutil.flatten<$NotificationλShape & {
  "source": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $SystemNotification = $.ObjectType<"notification::SystemNotification", $SystemNotificationλShape, null, [
  ...$Notification['__exclusives__'],
], "notification::SystemNotification">;
const $SystemNotification = $.makeType<$SystemNotification>(_.spec, "e46be406-b9ed-11f0-801c-033391b5c733", _.syntax.literal);

const SystemNotification: $.$expr_PathNode<$.TypeSet<$SystemNotification, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SystemNotification, $.Cardinality.Many), null);



export { DeliveryMethod, Status, Type, $AllReps, AllReps, $AllUsers, AllUsers, $Notification, Notification, $AuthoredNotification, AuthoredNotification, $MailingList, MailingList, $SystemNotification, SystemNotification };

type __defaultExports = {
  "DeliveryMethod": typeof DeliveryMethod;
  "Status": typeof Status;
  "Type": typeof Type;
  "AllReps": typeof AllReps;
  "AllUsers": typeof AllUsers;
  "Notification": typeof Notification;
  "AuthoredNotification": typeof AuthoredNotification;
  "MailingList": typeof MailingList;
  "SystemNotification": typeof SystemNotification
};
const __defaultExports: __defaultExports = {
  "DeliveryMethod": DeliveryMethod,
  "Status": Status,
  "Type": Type,
  "AllReps": AllReps,
  "AllUsers": AllUsers,
  "Notification": Notification,
  "AuthoredNotification": AuthoredNotification,
  "MailingList": MailingList,
  "SystemNotification": SystemNotification
};
export default __defaultExports;
