// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import _module__print_status from "./printing/print_status";
import _module__printer_status from "./printing/printer_status";
import type * as _default from "./default";
import type * as _std from "./std";
import type * as _users from "./users";
import type * as _printingprinter_status from "./printing/printer_status";
import type * as _printingprint_status from "./printing/print_status";
import type * as _sign_in from "./sign_in";
export type $Type = {
  "PLA": $.$expr_Literal<$Type>;
  "TPU": $.$expr_Literal<$Type>;
  "PETG": $.$expr_Literal<$Type>;
  "RESIN": $.$expr_Literal<$Type>;
} & $.EnumType<"printing::Type", ["PLA", "TPU", "PETG", "RESIN"]>;
const Type: $Type = $.makeType<$Type>(_.spec, "86700af8-bfc7-11f0-96a6-db1cf949f6d6", _.syntax.literal);

export type $AuditEntryλShape = $.typeutil.flatten<_default.$CreatedAtλShape & {
  "status": $.LinkDesc<$PrintStatus | $PrinterStatus, $.Cardinality.One, {}, false, false,  false, false>;
  "printer": $.LinkDesc<$Printer, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $AuditEntry = $.ObjectType<"printing::AuditEntry", $AuditEntryλShape, null, [
  ..._default.$CreatedAt['__exclusives__'],
], "printing::PrintAuditEntry" | "printing::PrinterAuditEntry">;
const $AuditEntry = $.makeType<$AuditEntry>(_.spec, "b8308fcc-bfc7-11f0-8248-47f85d666535", _.syntax.literal);

const AuditEntry: $.$expr_PathNode<$.TypeSet<$AuditEntry, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($AuditEntry, $.Cardinality.Many), null);

export type $PrintλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "gcode_path": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "stl_path": $.PropertyDesc<_std.$str, $.Cardinality.One, false, true, false, false>;
  "approved_by": $.LinkDesc<_users.$Rep, $.Cardinality.One, {}, false, false,  false, false>;
  "author": $.LinkDesc<_users.$User, $.Cardinality.One, {}, false, false,  false, false>;
  "duration": $.PropertyDesc<_std.$duration, $.Cardinality.One, false, false, false, false>;
  "mass": $.PropertyDesc<_std.$float32, $.Cardinality.One, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "type": $.PropertyDesc<$Type, $.Cardinality.One, false, false, false, false>;
  "on": $.LinkDesc<$PrintHistory, $.Cardinality.Many, {}, false, false,  false, false>;
  "<print[is printing::printer_status::Printing]": $.LinkDesc<_printingprinter_status.$Printing, $.Cardinality.Many, {}, false, false,  false, false>;
  "<print[is printing::print_status::Printing]": $.LinkDesc<_printingprint_status.$Printing, $.Cardinality.Many, {}, false, false,  false, false>;
  "<print[is printing::PrintAuditEntry]": $.LinkDesc<$PrintAuditEntry, $.Cardinality.Many, {}, false, false,  false, false>;
  "<prints[is printing::Printer]": $.LinkDesc<$Printer, $.Cardinality.Many, {}, false, false,  false, false>;
  "<print": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<prints": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Print = $.ObjectType<"printing::Print", $PrintλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "printing::Print">;
const $Print = $.makeType<$Print>(_.spec, "8689cd80-bfc7-11f0-8e53-c904f2aa15d3", _.syntax.literal);

const Print: $.$expr_PathNode<$.TypeSet<$Print, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Print, $.Cardinality.Many), null);

export type $PrintAuditEntryλShape = $.typeutil.flatten<Omit<$AuditEntryλShape, "status"> & {
  "status": $.LinkDesc<$PrintStatus, $.Cardinality.One, {}, false, false,  false, false>;
  "print": $.LinkDesc<$Print, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $PrintAuditEntry = $.ObjectType<"printing::PrintAuditEntry", $PrintAuditEntryλShape, null, [
  ...$AuditEntry['__exclusives__'],
], "printing::PrintAuditEntry">;
const $PrintAuditEntry = $.makeType<$PrintAuditEntry>(_.spec, "b84d7948-bfc7-11f0-9b21-693c90b7c77f", _.syntax.literal);

const PrintAuditEntry: $.$expr_PathNode<$.TypeSet<$PrintAuditEntry, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($PrintAuditEntry, $.Cardinality.Many), null);

export type $PrintHistoryλShape = $.typeutil.flatten<_default.$CreatedAtλShape & {
  "printer": $.LinkDesc<$Printer, $.Cardinality.One, {}, false, false,  false, false>;
  "status": $.LinkDesc<$PrintStatus, $.Cardinality.One, {}, false, false,  false, false>;
  "<on[is printing::Print]": $.LinkDesc<$Print, $.Cardinality.Many, {}, false, false,  false, false>;
  "<on": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $PrintHistory = $.ObjectType<"printing::PrintHistory", $PrintHistoryλShape, null, [
  ..._default.$CreatedAt['__exclusives__'],
], "printing::PrintHistory">;
const $PrintHistory = $.makeType<$PrintHistory>(_.spec, "b856b490-bfc7-11f0-9fae-3f6366ed8242", _.syntax.literal);

const PrintHistory: $.$expr_PathNode<$.TypeSet<$PrintHistory, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($PrintHistory, $.Cardinality.Many), null);

export type $PrintStatusλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "<status[is printing::PrintAuditEntry]": $.LinkDesc<$PrintAuditEntry, $.Cardinality.Many, {}, false, false,  false, false>;
  "<status[is printing::PrintHistory]": $.LinkDesc<$PrintHistory, $.Cardinality.Many, {}, false, false,  false, false>;
  "<status": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $PrintStatus = $.ObjectType<"printing::PrintStatus", $PrintStatusλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "printing::print_status::Cancelled" | "printing::print_status::Complete" | "printing::print_status::Failed" | "printing::print_status::Printing" | "printing::print_status::Queued">;
const $PrintStatus = $.makeType<$PrintStatus>(_.spec, "86862450-bfc7-11f0-94ef-a92498495bc6", _.syntax.literal);

const PrintStatus: $.$expr_PathNode<$.TypeSet<$PrintStatus, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($PrintStatus, $.Cardinality.Many), null);

export type $PrinterλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "location": $.LinkDesc<_sign_in.$Location, $.Cardinality.One, {}, false, false,  false, false>;
  "status": $.LinkDesc<$PrinterStatus, $.Cardinality.One, {}, false, false,  false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "remote_ip": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "type": $.PropertyDesc<$Type, $.Cardinality.AtLeastOne, false, false, false, false>;
  "prints": $.LinkDesc<$Print, $.Cardinality.Many, {}, false, true,  false, false>;
  "<printer[is printing::AuditEntry]": $.LinkDesc<$AuditEntry, $.Cardinality.Many, {}, false, false,  false, false>;
  "<printer[is printing::PrinterAuditEntry]": $.LinkDesc<$PrinterAuditEntry, $.Cardinality.Many, {}, false, false,  false, false>;
  "<printer[is printing::PrintAuditEntry]": $.LinkDesc<$PrintAuditEntry, $.Cardinality.Many, {}, false, false,  false, false>;
  "<printer[is printing::PrintHistory]": $.LinkDesc<$PrintHistory, $.Cardinality.Many, {}, false, false,  false, false>;
  "<printer": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Printer = $.ObjectType<"printing::Printer", $PrinterλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "printing::Printer">;
const $Printer = $.makeType<$Printer>(_.spec, "b8389226-bfc7-11f0-a6d3-0332cffcdd85", _.syntax.literal);

const Printer: $.$expr_PathNode<$.TypeSet<$Printer, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Printer, $.Cardinality.Many), null);

export type $PrinterAuditEntryλShape = $.typeutil.flatten<Omit<$AuditEntryλShape, "status"> & {
  "status": $.LinkDesc<$PrinterStatus, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $PrinterAuditEntry = $.ObjectType<"printing::PrinterAuditEntry", $PrinterAuditEntryλShape, null, [
  ...$AuditEntry['__exclusives__'],
], "printing::PrinterAuditEntry">;
const $PrinterAuditEntry = $.makeType<$PrinterAuditEntry>(_.spec, "b843f12a-bfc7-11f0-a3e3-0b86e431765a", _.syntax.literal);

const PrinterAuditEntry: $.$expr_PathNode<$.TypeSet<$PrinterAuditEntry, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($PrinterAuditEntry, $.Cardinality.Many), null);

export type $PrinterStatusλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "<status[is printing::Printer]": $.LinkDesc<$Printer, $.Cardinality.Many, {}, false, false,  false, false>;
  "<status[is printing::PrinterAuditEntry]": $.LinkDesc<$PrinterAuditEntry, $.Cardinality.Many, {}, false, false,  false, false>;
  "<status": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $PrinterStatus = $.ObjectType<"printing::PrinterStatus", $PrinterStatusλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "printing::printer_status::Disabled" | "printing::printer_status::Disconnected" | "printing::printer_status::Failed" | "printing::printer_status::Idle" | "printing::printer_status::Printing">;
const $PrinterStatus = $.makeType<$PrinterStatus>(_.spec, "b82e81be-bfc7-11f0-88f6-b55eaed57db8", _.syntax.literal);

const PrinterStatus: $.$expr_PathNode<$.TypeSet<$PrinterStatus, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($PrinterStatus, $.Cardinality.Many), null);



export { Type, $AuditEntry, AuditEntry, $Print, Print, $PrintAuditEntry, PrintAuditEntry, $PrintHistory, PrintHistory, $PrintStatus, PrintStatus, $Printer, Printer, $PrinterAuditEntry, PrinterAuditEntry, $PrinterStatus, PrinterStatus };

type __defaultExports = {
  "Type": typeof Type;
  "AuditEntry": typeof AuditEntry;
  "Print": typeof Print;
  "PrintAuditEntry": typeof PrintAuditEntry;
  "PrintHistory": typeof PrintHistory;
  "PrintStatus": typeof PrintStatus;
  "Printer": typeof Printer;
  "PrinterAuditEntry": typeof PrinterAuditEntry;
  "PrinterStatus": typeof PrinterStatus;
  "print_status": typeof _module__print_status;
  "printer_status": typeof _module__printer_status
};
const __defaultExports: __defaultExports = {
  "Type": Type,
  "AuditEntry": AuditEntry,
  "Print": Print,
  "PrintAuditEntry": PrintAuditEntry,
  "PrintHistory": PrintHistory,
  "PrintStatus": PrintStatus,
  "Printer": Printer,
  "PrinterAuditEntry": PrinterAuditEntry,
  "PrinterStatus": PrinterStatus,
  "print_status": _module__print_status,
  "printer_status": _module__printer_status
};
export default __defaultExports;
