// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _default from "./default";
import type * as _users from "./users";
import type * as _std from "./std";
import type * as _sign_in from "./sign_in";
import type * as _training from "./training";
export type $Selectability = {
  "UNTRAINED": $.$expr_Literal<$Selectability>;
  "REVOKED": $.$expr_Literal<$Selectability>;
  "EXPIRED": $.$expr_Literal<$Selectability>;
  "REPS_UNTRAINED": $.$expr_Literal<$Selectability>;
  "IN_PERSON_MISSING": $.$expr_Literal<$Selectability>;
} & $.EnumType<"tools::Selectability", ["UNTRAINED", "REVOKED", "EXPIRED", "REPS_UNTRAINED", "IN_PERSON_MISSING"]>;
const Selectability: $Selectability = $.makeType<$Selectability>(_.spec, "042f80c0-b9ee-11f0-a84b-65fe6f500dfe", _.syntax.literal);

export type $Status = {
  "NOMINAL": $.$expr_Literal<$Status>;
  "IN_USE": $.$expr_Literal<$Status>;
  "OUT_OF_ORDER": $.$expr_Literal<$Status>;
} & $.EnumType<"tools::Status", ["NOMINAL", "IN_USE", "OUT_OF_ORDER"]>;
const Status: $Status = $.makeType<$Status>(_.spec, "042f8d34-b9ee-11f0-b36b-0dc32d9afab1", _.syntax.literal);

export type $BookingλShape = $.typeutil.flatten<_default.$AuditableλShape & {
  "user": $.LinkDesc<_users.$User, $.Cardinality.One, {}, false, false,  false, false>;
  "ends_at": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, false>;
  "starts_at": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, false>;
  "duration": $.PropertyDesc<_std.$duration, $.Cardinality.One, false, true, false, false>;
  "cancelled": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne, false, false, false, false>;
  "tool": $.LinkDesc<$Tool, $.Cardinality.One, {}, false, false,  false, false>;
  "<bookings[is users::User]": $.LinkDesc<_users.$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<bookings[is users::Rep]": $.LinkDesc<_users.$Rep, $.Cardinality.Many, {}, false, false,  false, false>;
  "<bookings[is user]": $.LinkDesc<_default.$user, $.Cardinality.Many, {}, false, false,  false, false>;
  "<bookings[is tools::Tool]": $.LinkDesc<$Tool, $.Cardinality.Many, {}, false, false,  false, false>;
  "<bookings": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Booking = $.ObjectType<"tools::Booking", $BookingλShape, null, [
  ..._default.$Auditable['__exclusives__'],
], "tools::Booking">;
const $Booking = $.makeType<$Booking>(_.spec, "175ecee9-b9ee-11f0-8cac-8ddc81fbb551", _.syntax.literal);

const Booking: $.$expr_PathNode<$.TypeSet<$Booking, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Booking, $.Cardinality.Many), null);

export type $ToolλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "is_bookable": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "status": $.PropertyDesc<$Status, $.Cardinality.One, false, false, false, false>;
  "min_booking_time": $.PropertyDesc<_std.$duration, $.Cardinality.AtMostOne, false, false, false, true>;
  "location": $.LinkDesc<_sign_in.$Location, $.Cardinality.One, {}, false, false,  false, false>;
  "rep": $.LinkDesc<_training.$Training, $.Cardinality.AtLeastOne, {}, false, false,  false, false>;
  "training": $.LinkDesc<_training.$Training, $.Cardinality.AtLeastOne, {}, false, false,  false, false>;
  "borrowable": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "max_booking_daily": $.PropertyDesc<_std.$duration, $.Cardinality.AtMostOne, false, false, false, false>;
  "max_booking_weekly": $.PropertyDesc<_std.$duration, $.Cardinality.AtMostOne, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "quantity": $.PropertyDesc<_std.$int16, $.Cardinality.One, false, false, false, false>;
  "bookings": $.LinkDesc<$Booking, $.Cardinality.Many, {}, false, true,  false, false>;
  "<tool[is tools::Booking]": $.LinkDesc<$Booking, $.Cardinality.Many, {}, false, false,  false, false>;
  "<tool": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Tool = $.ObjectType<"tools::Tool", $ToolλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "tools::Tool">;
const $Tool = $.makeType<$Tool>(_.spec, "20a3c8f3-b9ee-11f0-b6c9-8328352b6208", _.syntax.literal);

const Tool: $.$expr_PathNode<$.TypeSet<$Tool, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Tool, $.Cardinality.Many), null);



export { Selectability, Status, $Booking, Booking, $Tool, Tool };

type __defaultExports = {
  "Selectability": typeof Selectability;
  "Status": typeof Status;
  "Booking": typeof Booking;
  "Tool": typeof Tool
};
const __defaultExports: __defaultExports = {
  "Selectability": Selectability,
  "Status": Status,
  "Booking": Booking,
  "Tool": Tool
};
export default __defaultExports;
