// GENERATED by @gel/generate v0.7.1
// This file is automatically generated from .edgeql query files.
// To make changes, edit the source .edgeql file and regenerate.

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _$default from "./default";
import type * as _users from "./users";
import type * as _stdcal from "./std/cal";
import type * as _event from "./event";
import type * as _tools from "./tools";
import type * as _sign_in from "./sign_in";
export type $AnswerType = {
  "SINGLE": $.$expr_Literal<$AnswerType>;
  "MULTI": $.$expr_Literal<$AnswerType>;
} & $.EnumType<"training::AnswerType", ["SINGLE", "MULTI"]>;
const AnswerType: $AnswerType = $.makeType<$AnswerType>(_.spec, "78cf6aa6-be5c-11f1-8a18-57d33e64c1fa", _.syntax.literal);

export type $ExpiresReturn = $.ScalarType<"std::json", unknown>;
const ExpiresReturn: $.scalarTypeWithConstructor<_std.$json, never> = $.makeType<$.scalarTypeWithConstructor<_std.$json, never>>(_.spec, "ca7f8231-be5c-11f1-a5b7-63ba8e91e7f5", _.syntax.literal);

export type $LocationName = {
  "MAINSPACE": $.$expr_Literal<$LocationName>;
  "HEARTSPACE": $.$expr_Literal<$LocationName>;
  "GEORGE_PORTER": $.$expr_Literal<$LocationName>;
} & $.EnumType<"training::LocationName", ["MAINSPACE", "HEARTSPACE", "GEORGE_PORTER"]>;
const LocationName: $LocationName = $.makeType<$LocationName>(_.spec, "78cf831e-be5c-11f1-91ae-5f25363bf567", _.syntax.literal);

export type $NextStep = {
  "DO_ONLINE": $.$expr_Literal<$NextStep>;
  "DO_IN_PERSON": $.$expr_Literal<$NextStep>;
  "DO_IN_PERSON_OR_REP_ONLINE": $.$expr_Literal<$NextStep>;
  "DO_REP_ONLINE": $.$expr_Literal<$NextStep>;
  "DO_IN_PERSON_OR_REP_IN_PERSON": $.$expr_Literal<$NextStep>;
  "DO_REP_IN_PERSON": $.$expr_Literal<$NextStep>;
  "NONE": $.$expr_Literal<$NextStep>;
} & $.EnumType<"training::NextStep", ["DO_ONLINE", "DO_IN_PERSON", "DO_IN_PERSON_OR_REP_ONLINE", "DO_REP_ONLINE", "DO_IN_PERSON_OR_REP_IN_PERSON", "DO_REP_IN_PERSON", "NONE"]>;
const NextStep: $NextStep = $.makeType<$NextStep>(_.spec, "ca7f94e7-be5c-11f1-b240-9ff17764227e", _.syntax.literal);

export type $Status = {
  "UNTRAINED": $.$expr_Literal<$Status>;
  "REVOKED": $.$expr_Literal<$Status>;
  "EXPIRED": $.$expr_Literal<$Status>;
  "ONLINE_COMPLETE": $.$expr_Literal<$Status>;
  "FULLY_COMPLETE": $.$expr_Literal<$Status>;
  "REP_ONLINE_COMPLETE_NO_IN_PERSON": $.$expr_Literal<$Status>;
  "USER_TRAINING_COMPLETE": $.$expr_Literal<$Status>;
  "REP_ONLINE_COMPLETE": $.$expr_Literal<$Status>;
} & $.EnumType<"training::Status", ["UNTRAINED", "REVOKED", "EXPIRED", "ONLINE_COMPLETE", "FULLY_COMPLETE", "REP_ONLINE_COMPLETE_NO_IN_PERSON", "USER_TRAINING_COMPLETE", "REP_ONLINE_COMPLETE"]>;
const Status: $Status = $.makeType<$Status>(_.spec, "ca7fac29-be5c-11f1-a107-234e918584bb", _.syntax.literal);

export type $AnswerλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "content": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "correct": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "<answers[is training::Question]": $.LinkDesc<$Question, $.Cardinality.Many, {}, false, false,  false, false>;
  "<answers": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Answer = $.ObjectType<"training::Answer", $AnswerλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "training::Answer">;
const $Answer = $.makeType<$Answer>(_.spec, "7a0f6f74-be5c-11f1-b179-2f433d299506", _.syntax.literal);

const Answer: $.$expr_PathNode<$.TypeSet<$Answer, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Answer, $.Cardinality.Many), null);

export type $InteractableλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "content": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "enabled": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "index": $.PropertyDesc<_std.$int16, $.Cardinality.One, false, false, false, false>;
  "parent": $.LinkDesc<$Training, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $Interactable = $.ObjectType<"training::Interactable", $InteractableλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {parent: {__element__: $Training, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },index: {__element__: _std.$int16, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "training::TrainingPage" | "training::Page" | "training::Question">;
const $Interactable = $.makeType<$Interactable>(_.spec, "78b7b246-be5c-11f1-b01c-3bdcdf3463de", _.syntax.literal);

const Interactable: $.$expr_PathNode<$.TypeSet<$Interactable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Interactable, $.Cardinality.Many), null);

export type $TrainingPageλShape = $.typeutil.flatten<$InteractableλShape & {
  "duration": $.PropertyDesc<_std.$duration, $.Cardinality.AtMostOne, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<pages[is training::Training]": $.LinkDesc<$Training, $.Cardinality.Many, {}, false, false,  false, false>;
  "<pages": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $TrainingPage = $.ObjectType<"training::TrainingPage", $TrainingPageλShape, null, [
  ...$Interactable['__exclusives__'],
], "training::TrainingPage" | "training::Page">;
const $TrainingPage = $.makeType<$TrainingPage>(_.spec, "78b9be03-be5c-11f1-a3c4-cd08694ffbed", _.syntax.literal);

const TrainingPage: $.$expr_PathNode<$.TypeSet<$TrainingPage, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($TrainingPage, $.Cardinality.Many), null);

export type $PageλShape = $.typeutil.flatten<$TrainingPageλShape & {
}>;
type $Page = $.ObjectType<"training::Page", $PageλShape, null, [
  ...$TrainingPage['__exclusives__'],
], "training::Page">;
const $Page = $.makeType<$Page>(_.spec, "78ce9eb4-be5c-11f1-b297-e33ffc54d1c5", _.syntax.literal);

const Page: $.$expr_PathNode<$.TypeSet<$Page, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Page, $.Cardinality.Many), null);

export type $QuestionλShape = $.typeutil.flatten<$InteractableλShape & {
  "answers": $.LinkDesc<$Answer, $.Cardinality.AtLeastOne, {}, false, false,  false, false>;
  "type": $.PropertyDesc<$AnswerType, $.Cardinality.One, false, false, false, false>;
  "<questions[is training::Training]": $.LinkDesc<$Training, $.Cardinality.Many, {}, false, false,  false, false>;
  "<questions": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Question = $.ObjectType<"training::Question", $QuestionλShape, null, [
  ...$Interactable['__exclusives__'],
], "training::Question">;
const $Question = $.makeType<$Question>(_.spec, "7b5e6729-be5c-11f1-9c08-d9ab6441535d", _.syntax.literal);

const Question: $.$expr_PathNode<$.TypeSet<$Question, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Question, $.Cardinality.Many), null);

export type $SessionλShape = $.typeutil.flatten<_$default.$AuditableλShape & {
  "training": $.LinkDesc<$Training, $.Cardinality.One, {}, false, false,  false, false>;
  "index": $.PropertyDesc<_std.$int16, $.Cardinality.One, false, false, false, true>;
  "user": $.LinkDesc<_users.$User, $.Cardinality.One, {}, false, false,  false, false>;
  "next_section": $.LinkDesc<$TrainingPage | $Question, $.Cardinality.AtMostOne, {}, false, true,  false, false>;
}>;
type $Session = $.ObjectType<"training::Session", $SessionλShape, null, [
  ..._$default.$Auditable['__exclusives__'],
  {user: {__element__: _users.$User, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },training: {__element__: $Training, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "training::Session">;
const $Session = $.makeType<$Session>(_.spec, "7a97eefa-be5c-11f1-9816-b7ad8ce9d6b8", _.syntax.literal);

const Session: $.$expr_PathNode<$.TypeSet<$Session, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Session, $.Cardinality.Many), null);

export type $TrainingλShape = $.typeutil.flatten<_$default.$AuditableλShape & {
  "rep": $.LinkDesc<$Training, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "in_person": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "locations": $.PropertyDesc<$LocationName, $.Cardinality.Many, false, false, false, false>;
  "pages": $.LinkDesc<$TrainingPage, $.Cardinality.Many, {}, false, false,  false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "compulsory": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "enabled": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "icon_url": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "training_lockout": $.PropertyDesc<_std.$duration, $.Cardinality.AtMostOne, false, false, false, false>;
  "questions": $.LinkDesc<$Question, $.Cardinality.Many, {}, false, false,  false, false>;
  "sections": $.LinkDesc<$TrainingPage | $Question, $.Cardinality.Many, {}, false, true,  false, false>;
  "expires_after": $.PropertyDesc<_stdcal.$relative_duration, $.Cardinality.One, false, false, false, true>;
  "<rep[is training::Training]": $.LinkDesc<$Training, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training[is training::Session]": $.LinkDesc<$Session, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent[is training::Interactable]": $.LinkDesc<$Interactable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent[is training::TrainingPage]": $.LinkDesc<$TrainingPage, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent[is training::Page]": $.LinkDesc<$Page, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent[is training::Question]": $.LinkDesc<$Question, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training[is users::User]": $.LinkDesc<_users.$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<supervisable_training[is users::Rep]": $.LinkDesc<_users.$Rep, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training[is users::Rep]": $.LinkDesc<_users.$Rep, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training[is user]": $.LinkDesc<_$default.$user, $.Cardinality.Many, {}, false, false,  false, false>;
  "<required_training[is event::Event]": $.LinkDesc<_event.$Event, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training[is tools::Tool]": $.LinkDesc<_tools.$Tool, $.Cardinality.Many, {}, false, false,  false, false>;
  "<rep[is tools::Tool]": $.LinkDesc<_tools.$Tool, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training[is tools::GroupedTool]": $.LinkDesc<_tools.$GroupedTool, $.Cardinality.Many, {}, false, false,  false, false>;
  "<supervisable_training[is sign_in::Location]": $.LinkDesc<_sign_in.$Location, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<rep": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<required_training": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<supervisable_training": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Training = $.ObjectType<"training::Training", $TrainingλShape, null, [
  ..._$default.$Auditable['__exclusives__'],
], "training::Training">;
const $Training = $.makeType<$Training>(_.spec, "7a3e04d1-be5c-11f1-b693-69c8b1ef3d7e", _.syntax.literal);

const Training: $.$expr_PathNode<$.TypeSet<$Training, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Training, $.Cardinality.Many), null);

type get_statusλFuncExpr<
  NamedArgs extends {
    "collapse"?: _.castMaps.orScalarLiteral<$.TypeSet<_std.$bool>>,
  },
  P1 extends $.TypeSet<$Training>,
  P2 extends $.TypeSet<_users.$User>,
> = $.$expr_Function<
  $.NamedTupleType<{care: _std.$int64, value: _std.$int64, status: $Status, next_step: $NextStep}>, $.cardutil.overrideLowerBound<$.cardutil.multiplyCardinalities<$.cardutil.multiplyCardinalities<$.cardutil.paramCardinality<P1>, $.cardutil.paramCardinality<P2>>, $.cardutil.optionalParamCardinality<NamedArgs["collapse"]>>, "Zero">
>;
type get_statusλFuncExpr2<
  P1 extends $.TypeSet<$Training>,
  P2 extends $.TypeSet<_users.$User>,
> = $.$expr_Function<
  $.NamedTupleType<{care: _std.$int64, value: _std.$int64, status: $Status, next_step: $NextStep}>, $.cardutil.overrideLowerBound<$.cardutil.multiplyCardinalities<$.cardutil.paramCardinality<P1>, $.cardutil.paramCardinality<P2>>, "Zero">
>;
function get_status<
  NamedArgs extends {
    "collapse"?: _.castMaps.orScalarLiteral<$.TypeSet<_std.$bool>>,
  },
  P1 extends $.TypeSet<$Training>,
  P2 extends $.TypeSet<_users.$User>,
>(
  namedArgs: NamedArgs,
  training: P1,
  user: P2,
): get_statusλFuncExpr<NamedArgs, P1, P2>;
function get_status<
  P1 extends $.TypeSet<$Training>,
  P2 extends $.TypeSet<_users.$User>,
>(
  training: P1,
  user: P2,
): get_statusλFuncExpr2<P1, P2>;
function get_status(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('training::get_status', args, _.spec, [
    {args: [{typeId: "7a3e04d1-be5c-11f1-b693-69c8b1ef3d7e", optional: false, setoftype: false, variadic: false}, {typeId: "7890cb83-be5c-11f1-8649-95fe64c2e859", optional: false, setoftype: false, variadic: false}], namedArgs: {"collapse": {typeId: "00000000-0000-0000-0000-000000000109", optional: true, setoftype: false, variadic: false}}, returnTypeId: "71a32e55-be5d-11f1-bc77-c5cec035ae2d", returnTypemod: "OptionalType"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "training::get_status",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

type get_expiry_datesλFuncExpr<
  P1 extends $.TypeSet<_users.$User>,
> = $.$expr_Function<
  $ExpiresReturn, $.cardutil.paramCardinality<P1>
>;
function get_expiry_dates<
  P1 extends $.TypeSet<_users.$User>,
>(
  user: P1,
): get_expiry_datesλFuncExpr<P1>;
function get_expiry_dates(...args: any[]) {
  const {returnType, cardinality, args: positionalArgs, namedArgs} = _.syntax.$resolveOverload('training::get_expiry_dates', args, _.spec, [
    {args: [{typeId: "7890cb83-be5c-11f1-8649-95fe64c2e859", optional: false, setoftype: false, variadic: false}], returnTypeId: "ca7f8231-be5c-11f1-a5b7-63ba8e91e7f5"},
  ]);
  return _.syntax.$expressionify({
    __kind__: $.ExpressionKind.Function,
    __element__: returnType,
    __cardinality__: cardinality,
    __name__: "training::get_expiry_dates",
    __args__: positionalArgs,
    __namedargs__: namedArgs,
  }) as any;
};

const $training__globals: {  COLLAPSED_LOOKUPS: _.syntax.$expr_Global<
              // "training::COLLAPSED_LOOKUPS",
              $.NamedTupleType<{care: _std.$int64, value: _std.$int64, status: $Status, next_step: $NextStep}>,
              $.Cardinality.AtLeastOne
              >,  LOOKUPS: _.syntax.$expr_Global<
              // "training::LOOKUPS",
              $.NamedTupleType<{care: _std.$int64, value: _std.$int64, status: $Status, next_step: $NextStep}>,
              $.Cardinality.AtLeastOne
              >} = {  COLLAPSED_LOOKUPS: _.syntax.makeGlobal(
              "training::COLLAPSED_LOOKUPS",
              $.makeType(_.spec, "71a334b1-be5d-11f1-af59-e1fdea5c780f", _.syntax.literal),
              $.Cardinality.AtLeastOne) as any,  LOOKUPS: _.syntax.makeGlobal(
              "training::LOOKUPS",
              $.makeType(_.spec, "71ae97e5-be5d-11f1-9bb5-67052df7e8e9", _.syntax.literal),
              $.Cardinality.AtLeastOne) as any};



export { AnswerType, ExpiresReturn, LocationName, NextStep, Status, $Answer, Answer, $Interactable, Interactable, $TrainingPage, TrainingPage, $Page, Page, $Question, Question, $Session, Session, $Training, Training };

type __defaultExports = {
  "AnswerType": typeof AnswerType;
  "ExpiresReturn": typeof ExpiresReturn;
  "LocationName": typeof LocationName;
  "NextStep": typeof NextStep;
  "Status": typeof Status;
  "Answer": typeof Answer;
  "Interactable": typeof Interactable;
  "TrainingPage": typeof TrainingPage;
  "Page": typeof Page;
  "Question": typeof Question;
  "Session": typeof Session;
  "Training": typeof Training;
  "get_status": typeof get_status;
  "get_expiry_dates": typeof get_expiry_dates;
  "global": typeof $training__globals
};
const __defaultExports: __defaultExports = {
  "AnswerType": AnswerType,
  "ExpiresReturn": ExpiresReturn,
  "LocationName": LocationName,
  "NextStep": NextStep,
  "Status": Status,
  "Answer": Answer,
  "Interactable": Interactable,
  "TrainingPage": TrainingPage,
  "Page": Page,
  "Question": Question,
  "Session": Session,
  "Training": Training,
  "get_status": get_status,
  "get_expiry_dates": get_expiry_dates,
  "global": $training__globals
};
export default __defaultExports;
