// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _default from "./default";
import type * as _users from "./users";
import type * as _sign_in from "./sign_in";
import type * as _tools from "./tools";
export type $AnswerType = {
  "SINGLE": $.$expr_Literal<$AnswerType>;
  "MULTI": $.$expr_Literal<$AnswerType>;
} & $.EnumType<"training::AnswerType", ["SINGLE", "MULTI"]>;
const AnswerType: $AnswerType = $.makeType<$AnswerType>(_.spec, "df176efa-b9ed-11f0-b5c0-0b7a5dd9d0ea", _.syntax.literal);

export type $LocationName = {
  "MAINSPACE": $.$expr_Literal<$LocationName>;
  "HEARTSPACE": $.$expr_Literal<$LocationName>;
  "GEORGE_PORTER": $.$expr_Literal<$LocationName>;
} & $.EnumType<"training::LocationName", ["MAINSPACE", "HEARTSPACE", "GEORGE_PORTER"]>;
const LocationName: $LocationName = $.makeType<$LocationName>(_.spec, "df177cb1-b9ed-11f0-8cc0-9f2e0616b5e4", _.syntax.literal);

export type $AnswerλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "content": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "correct": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "<answers[is training::Question]": $.LinkDesc<$Question, $.Cardinality.Many, {}, false, false,  false, false>;
  "<answers": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Answer = $.ObjectType<"training::Answer", $AnswerλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "training::Answer">;
const $Answer = $.makeType<$Answer>(_.spec, "e0156859-b9ed-11f0-8038-a38aba211478", _.syntax.literal);

const Answer: $.$expr_PathNode<$.TypeSet<$Answer, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Answer, $.Cardinality.Many), null);

export type $InteractableλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "content": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "enabled": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "index": $.PropertyDesc<_std.$int16, $.Cardinality.One, false, false, false, false>;
  "parent": $.LinkDesc<$Training, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $Interactable = $.ObjectType<"training::Interactable", $InteractableλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {parent: {__element__: $Training, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },index: {__element__: _std.$int16, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "training::TrainingPage" | "training::Page" | "training::Question">;
const $Interactable = $.makeType<$Interactable>(_.spec, "def396e5-b9ed-11f0-86f8-d726d3091d2d", _.syntax.literal);

const Interactable: $.$expr_PathNode<$.TypeSet<$Interactable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Interactable, $.Cardinality.Many), null);

export type $TrainingPageλShape = $.typeutil.flatten<$InteractableλShape & {
  "duration": $.PropertyDesc<_std.$duration, $.Cardinality.AtMostOne, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "<pages[is training::Training]": $.LinkDesc<$Training, $.Cardinality.Many, {}, false, false,  false, false>;
  "<pages": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $TrainingPage = $.ObjectType<"training::TrainingPage", $TrainingPageλShape, null, [
  ...$Interactable['__exclusives__'],
], "training::TrainingPage" | "training::Page">;
const $TrainingPage = $.makeType<$TrainingPage>(_.spec, "def4c583-b9ed-11f0-91b0-390adf54d00d", _.syntax.literal);

const TrainingPage: $.$expr_PathNode<$.TypeSet<$TrainingPage, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($TrainingPage, $.Cardinality.Many), null);

export type $PageλShape = $.typeutil.flatten<$TrainingPageλShape & {
}>;
type $Page = $.ObjectType<"training::Page", $PageλShape, null, [
  ...$TrainingPage['__exclusives__'],
], "training::Page">;
const $Page = $.makeType<$Page>(_.spec, "df15d594-b9ed-11f0-9abd-1fab6db1dde4", _.syntax.literal);

const Page: $.$expr_PathNode<$.TypeSet<$Page, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Page, $.Cardinality.Many), null);

export type $QuestionλShape = $.typeutil.flatten<$InteractableλShape & {
  "answers": $.LinkDesc<$Answer, $.Cardinality.AtLeastOne, {}, false, false,  false, false>;
  "type": $.PropertyDesc<$AnswerType, $.Cardinality.One, false, false, false, false>;
  "<questions[is training::Training]": $.LinkDesc<$Training, $.Cardinality.Many, {}, false, false,  false, false>;
  "<questions": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Question = $.ObjectType<"training::Question", $QuestionλShape, null, [
  ...$Interactable['__exclusives__'],
], "training::Question">;
const $Question = $.makeType<$Question>(_.spec, "e0c85a28-b9ed-11f0-8240-3b19b9eca796", _.syntax.literal);

const Question: $.$expr_PathNode<$.TypeSet<$Question, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Question, $.Cardinality.Many), null);

export type $SessionλShape = $.typeutil.flatten<_default.$AuditableλShape & {
  "training": $.LinkDesc<$Training, $.Cardinality.One, {}, false, false,  false, false>;
  "index": $.PropertyDesc<_std.$int16, $.Cardinality.One, false, false, false, true>;
  "user": $.LinkDesc<_users.$User, $.Cardinality.One, {}, false, false,  false, false>;
  "next_section": $.LinkDesc<$TrainingPage | $Question, $.Cardinality.AtMostOne, {}, false, true,  false, false>;
}>;
type $Session = $.ObjectType<"training::Session", $SessionλShape, null, [
  ..._default.$Auditable['__exclusives__'],
  {user: {__element__: _users.$User, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },training: {__element__: $Training, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "training::Session">;
const $Session = $.makeType<$Session>(_.spec, "e087832c-b9ed-11f0-8341-21630ada765e", _.syntax.literal);

const Session: $.$expr_PathNode<$.TypeSet<$Session, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Session, $.Cardinality.Many), null);

export type $TrainingλShape = $.typeutil.flatten<_default.$AuditableλShape & {
  "rep": $.LinkDesc<$Training, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "in_person": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, false>;
  "locations": $.PropertyDesc<$LocationName, $.Cardinality.Many, false, false, false, false>;
  "pages": $.LinkDesc<$TrainingPage, $.Cardinality.Many, {}, false, false,  false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "compulsory": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "enabled": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "expires_after": $.PropertyDesc<_std.$duration, $.Cardinality.AtMostOne, false, false, false, false>;
  "icon_url": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "training_lockout": $.PropertyDesc<_std.$duration, $.Cardinality.AtMostOne, false, false, false, false>;
  "questions": $.LinkDesc<$Question, $.Cardinality.Many, {}, false, false,  false, false>;
  "sections": $.LinkDesc<$TrainingPage | $Question, $.Cardinality.Many, {}, false, true,  false, false>;
  "<rep[is training::Training]": $.LinkDesc<$Training, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training[is training::Session]": $.LinkDesc<$Session, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent[is training::Interactable]": $.LinkDesc<$Interactable, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent[is training::TrainingPage]": $.LinkDesc<$TrainingPage, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent[is training::Page]": $.LinkDesc<$Page, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent[is training::Question]": $.LinkDesc<$Question, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training[is users::User]": $.LinkDesc<_users.$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training[is users::Rep]": $.LinkDesc<_users.$Rep, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training[is user]": $.LinkDesc<_default.$user, $.Cardinality.Many, {}, false, false,  false, false>;
  "<supervisable_training[is users::Rep]": $.LinkDesc<_users.$Rep, $.Cardinality.Many, {}, false, false,  false, false>;
  "<supervisable_training[is sign_in::Location]": $.LinkDesc<_sign_in.$Location, $.Cardinality.Many, {}, false, false,  false, false>;
  "<rep[is tools::Tool]": $.LinkDesc<_tools.$Tool, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training[is tools::Tool]": $.LinkDesc<_tools.$Tool, $.Cardinality.Many, {}, false, false,  false, false>;
  "<parent": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<rep": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<supervisable_training": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<training": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Training = $.ObjectType<"training::Training", $TrainingλShape, null, [
  ..._default.$Auditable['__exclusives__'],
], "training::Training">;
const $Training = $.makeType<$Training>(_.spec, "e02fb580-b9ed-11f0-9697-9fafe92b60e4", _.syntax.literal);

const Training: $.$expr_PathNode<$.TypeSet<$Training, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Training, $.Cardinality.Many), null);



export { AnswerType, LocationName, $Answer, Answer, $Interactable, Interactable, $TrainingPage, TrainingPage, $Page, Page, $Question, Question, $Session, Session, $Training, Training };

type __defaultExports = {
  "AnswerType": typeof AnswerType;
  "LocationName": typeof LocationName;
  "Answer": typeof Answer;
  "Interactable": typeof Interactable;
  "TrainingPage": typeof TrainingPage;
  "Page": typeof Page;
  "Question": typeof Question;
  "Session": typeof Session;
  "Training": typeof Training
};
const __defaultExports: __defaultExports = {
  "AnswerType": AnswerType,
  "LocationName": LocationName,
  "Answer": Answer,
  "Interactable": Interactable,
  "TrainingPage": TrainingPage,
  "Page": Page,
  "Question": Question,
  "Session": Session,
  "Training": Training
};
export default __defaultExports;
