api:
  dashboard: true
  insecure: true

entryPoints:
  http:
    address: :80
  https:
    address: :443

providers:
  docker:
    exposedByDefault: false
    endpoint: tcp://dockerproxy:2375
    network: backend_tier

log:
  level: DEBUG

