apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secrets.yaml
  - certificate.yaml
  - deployment.yaml
  - service.yaml
  - pvc.yaml
  - cluster.yaml
