apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gel-data
  namespace: gel
  labels:
    app: gel
    layer: infrastructure
    component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi 