apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gel-server-password
  namespace: gel
  labels:
    app: gel
    layer: infrastructure
    component: database
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/jnqqroba24ftsxn3yc5r76lpca/items/gel-server-password
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gel-postgres-superuser
  namespace: gel
  labels:
    app: gel
    layer: infrastructure
    component: database
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/jnqqroba24ftsxn3yc5r76lpca/items/gel-postgres-superuser
---
apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: gel-postgres-user
  namespace: gel
  labels:
    app: gel
    layer: infrastructure
    component: database
  annotations:
    operator.1password.io/auto-restart: "true"
spec:
  itemPath: vaults/jnqqroba24ftsxn3yc5r76lpca/items/gel-postgres-user