apiVersion: v1
kind: Service
metadata:
  name: gel
  namespace: gel
  labels:
    app: gel
    layer: infrastructure
    component: database
spec:
  selector:
    app: gel
  ports:
    - name: https
      protocol: TCP
      port: 5656
      targetPort: 5656
  type: ClusterIP 