apiVersion: v1
kind: Service
metadata:
  name: mine-service
  namespace: ignis
  labels:
    app: mine
spec:
  selector:
    app: mine
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
  type: ClusterIP 