CREATE MIGRATION m1yqszbktwtiajorhzlor4van7jebzrzervdhwd73co52es2fz2csa
    ONTO m16z45eg7gfx4hmxufnrcksk6lnsdapnga4tfy5ngvke42tbgedwna
{
  ALTER SCALAR TYPE tools::Selectability EXTENDING enum<UNTRAINED, REVOKED, EXPIRED, DO_IN_PERSON, DO_IN_PERSON_OR_REP_ONLINE, DO_REP_ONLINE, DO_IN_PERSON_OR_REP_IN_PERSON, DO_REP_IN_PERSON, REPS_UNTRAINED, TOOL_BROKEN, NONE>;
};
