CREATE MIGRATION m13n7nfz5m2skho7w6i2nt2dh44s4rkrtwpywfxsw4olympj5jbrsq
    ONTO m15mxz6k5noylgh5ciacghn4bb5jsf5fvjqli3g446kthqjh43yofa
{
  ALTER SCALAR TYPE tools::Selectability EXTENDING enum<DO_ONLINE, REVOKED, EXPIRED, DO_IN_PERSON, NONE_REMAINING, DO_IN_PERSON_OR_REP_ONLINE, DO_REP_ONLINE, DO_IN_PERSON_OR_REP_IN_PERSON, DO_REP_IN_PERSON, REPS_UNTRAINED, TOOL_BROKEN, NONE>;
};
