apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: valkey
  labels:
    app: valkey
    layer: infrastructure
    component: database
spec:
  selector:
    app: valkey
  ports:
  - name: valkey
    port: 6379
    targetPort: 6379
  - name: cluster
    port: 16379
    targetPort: 16379
  clusterIP: None  # Headless service for StatefulSet DNS 