// GENERATED by @gel/generate v0.6.2

import * as $ from "../../reflection";
import * as _ from "../../imports";
import type * as _printing from "../printing";
import type * as _std from "../std";
export type $FailureReason = {
  "MAIN_CONTROLLER_BOARD": $.$expr_Literal<$FailureReason>;
  "POWER_SUPPLY": $.$expr_Literal<$FailureReason>;
  "DISPLAY_BOARD": $.$expr_Literal<$FailureReason>;
  "WIFI_MODULE": $.$expr_Literal<$FailureReason>;
  "HOTEND_THERMISTOR": $.$expr_Literal<$FailureReason>;
  "HEATBED_THERMISTOR": $.$expr_Literal<$FailureReason>;
  "HOTEND_HEATER_CARTRIDGE": $.$expr_Literal<$FailureReason>;
  "HEATBED_HEATING_ELEMENT": $.$expr_Literal<$FailureReason>;
  "HEATER_BLOCK": $.$expr_Literal<$FailureReason>;
  "EXTRUDER_MOTOR": $.$expr_Literal<$FailureReason>;
  "X_AXIS_MOTOR": $.$expr_Literal<$FailureReason>;
  "Y_AXIS_MOTOR": $.$expr_Literal<$FailureReason>;
  "Z_AXIS_MOTOR": $.$expr_Literal<$FailureReason>;
  "LINEAR_RAILS": $.$expr_Literal<$FailureReason>;
  "LINEAR_BEARINGS": $.$expr_Literal<$FailureReason>;
  "BELT_SYSTEM": $.$expr_Literal<$FailureReason>;
  "PULLEYS": $.$expr_Literal<$FailureReason>;
  "LEAD_SCREW_NUT": $.$expr_Literal<$FailureReason>;
  "HOTEND_FAN": $.$expr_Literal<$FailureReason>;
  "PART_COOLING_FAN": $.$expr_Literal<$FailureReason>;
  "CHAMBER_FAN": $.$expr_Literal<$FailureReason>;
  "POWER_SUPPLY_FAN": $.$expr_Literal<$FailureReason>;
  "NOZZLE": $.$expr_Literal<$FailureReason>;
  "HEAT_BREAK": $.$expr_Literal<$FailureReason>;
  "HEAT_SINK": $.$expr_Literal<$FailureReason>;
  "EXTRUDER_GEARS": $.$expr_Literal<$FailureReason>;
  "BOWDEN_TUBE": $.$expr_Literal<$FailureReason>;
  "FILAMENT_SENSOR": $.$expr_Literal<$FailureReason>;
  "BED_LEVELING_SENSOR": $.$expr_Literal<$FailureReason>;
  "DOOR_SENSOR": $.$expr_Literal<$FailureReason>;
  "CRASH_DETECTION_SENSOR": $.$expr_Literal<$FailureReason>;
  "POWER_PANIC_SENSOR": $.$expr_Literal<$FailureReason>;
  "PRINT_BED_SURFACE": $.$expr_Literal<$FailureReason>;
  "BED_LEVELLING_SPRINGS": $.$expr_Literal<$FailureReason>;
  "BED_MOUNTING_HARDWARE": $.$expr_Literal<$FailureReason>;
  "HOTEND_WIRING": $.$expr_Literal<$FailureReason>;
  "HEATBED_WIRING": $.$expr_Literal<$FailureReason>;
  "MOTOR_WIRING": $.$expr_Literal<$FailureReason>;
  "MAIN_POWER_CABLE": $.$expr_Literal<$FailureReason>;
  "USB_CONNECTION": $.$expr_Literal<$FailureReason>;
  "FRAME_COMPONENTS": $.$expr_Literal<$FailureReason>;
  "SMOOTH_RODS": $.$expr_Literal<$FailureReason>;
  "ENCLOSURE_PANELS": $.$expr_Literal<$FailureReason>;
  "FILAMENT_FEEDING": $.$expr_Literal<$FailureReason>;
} & $.EnumType<"printing::printer_status::FailureReason", ["MAIN_CONTROLLER_BOARD", "POWER_SUPPLY", "DISPLAY_BOARD", "WIFI_MODULE", "HOTEND_THERMISTOR", "HEATBED_THERMISTOR", "HOTEND_HEATER_CARTRIDGE", "HEATBED_HEATING_ELEMENT", "HEATER_BLOCK", "EXTRUDER_MOTOR", "X_AXIS_MOTOR", "Y_AXIS_MOTOR", "Z_AXIS_MOTOR", "LINEAR_RAILS", "LINEAR_BEARINGS", "BELT_SYSTEM", "PULLEYS", "LEAD_SCREW_NUT", "HOTEND_FAN", "PART_COOLING_FAN", "CHAMBER_FAN", "POWER_SUPPLY_FAN", "NOZZLE", "HEAT_BREAK", "HEAT_SINK", "EXTRUDER_GEARS", "BOWDEN_TUBE", "FILAMENT_SENSOR", "BED_LEVELING_SENSOR", "DOOR_SENSOR", "CRASH_DETECTION_SENSOR", "POWER_PANIC_SENSOR", "PRINT_BED_SURFACE", "BED_LEVELLING_SPRINGS", "BED_MOUNTING_HARDWARE", "HOTEND_WIRING", "HEATBED_WIRING", "MOTOR_WIRING", "MAIN_POWER_CABLE", "USB_CONNECTION", "FRAME_COMPONENTS", "SMOOTH_RODS", "ENCLOSURE_PANELS", "FILAMENT_FEEDING"]>;
const FailureReason: $FailureReason = $.makeType<$FailureReason>(_.spec, "042f68c3-b9ee-11f0-89e6-e1d73a3ae0f6", _.syntax.literal);

export type $DisabledλShape = $.typeutil.flatten<_printing.$PrinterStatusλShape & {
}>;
type $Disabled = $.ObjectType<"printing::printer_status::Disabled", $DisabledλShape, null, [
  ..._printing.$PrinterStatus['__exclusives__'],
], "printing::printer_status::Disabled">;
const $Disabled = $.makeType<$Disabled>(_.spec, "180e79a3-b9ee-11f0-a97e-bd2e1d00dfa4", _.syntax.literal);

const Disabled: $.$expr_PathNode<$.TypeSet<$Disabled, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Disabled, $.Cardinality.Many), null);

export type $DisconnectedλShape = $.typeutil.flatten<_printing.$PrinterStatusλShape & {
}>;
type $Disconnected = $.ObjectType<"printing::printer_status::Disconnected", $DisconnectedλShape, null, [
  ..._printing.$PrinterStatus['__exclusives__'],
], "printing::printer_status::Disconnected">;
const $Disconnected = $.makeType<$Disconnected>(_.spec, "180f9073-b9ee-11f0-a941-8560fd791911", _.syntax.literal);

const Disconnected: $.$expr_PathNode<$.TypeSet<$Disconnected, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Disconnected, $.Cardinality.Many), null);

export type $FailedλShape = $.typeutil.flatten<_printing.$PrinterStatusλShape & {
  "note": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "reason": $.PropertyDesc<$FailureReason, $.Cardinality.One, false, false, false, false>;
}>;
type $Failed = $.ObjectType<"printing::printer_status::Failed", $FailedλShape, null, [
  ..._printing.$PrinterStatus['__exclusives__'],
], "printing::printer_status::Failed">;
const $Failed = $.makeType<$Failed>(_.spec, "1810a485-b9ee-11f0-80cb-2507a824d136", _.syntax.literal);

const Failed: $.$expr_PathNode<$.TypeSet<$Failed, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Failed, $.Cardinality.Many), null);

export type $IdleλShape = $.typeutil.flatten<_printing.$PrinterStatusλShape & {
}>;
type $Idle = $.ObjectType<"printing::printer_status::Idle", $IdleλShape, null, [
  ..._printing.$PrinterStatus['__exclusives__'],
], "printing::printer_status::Idle">;
const $Idle = $.makeType<$Idle>(_.spec, "18119ff3-b9ee-11f0-afca-099d28ce1796", _.syntax.literal);

const Idle: $.$expr_PathNode<$.TypeSet<$Idle, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Idle, $.Cardinality.Many), null);

export type $PrintingλShape = $.typeutil.flatten<_printing.$PrinterStatusλShape & {
  "print": $.LinkDesc<_printing.$Print, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $Printing = $.ObjectType<"printing::printer_status::Printing", $PrintingλShape, null, [
  ..._printing.$PrinterStatus['__exclusives__'],
], "printing::printer_status::Printing">;
const $Printing = $.makeType<$Printing>(_.spec, "1812817b-b9ee-11f0-b9dc-c76733e5d204", _.syntax.literal);

const Printing: $.$expr_PathNode<$.TypeSet<$Printing, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Printing, $.Cardinality.Many), null);



export { FailureReason, $Disabled, Disabled, $Disconnected, Disconnected, $Failed, Failed, $Idle, Idle, $Printing, Printing };

type __defaultExports = {
  "FailureReason": typeof FailureReason;
  "Disabled": typeof Disabled;
  "Disconnected": typeof Disconnected;
  "Failed": typeof Failed;
  "Idle": typeof Idle;
  "Printing": typeof Printing
};
const __defaultExports: __defaultExports = {
  "FailureReason": FailureReason,
  "Disabled": Disabled,
  "Disconnected": Disconnected,
  "Failed": Failed,
  "Idle": Idle,
  "Printing": Printing
};
export default __defaultExports;
