// GENERATED by @edgedb/generate v0.5.6

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
export type $CreatedAtλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "created_at": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, true, true>;
}>;
type $CreatedAt = $.ObjectType<"default::CreatedAt", $CreatedAtλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $CreatedAt = $.makeType<$CreatedAt>(_.spec, "33123b54-8a32-11ef-9868-4bc3744c6ba0", _.syntax.literal);

const CreatedAt: $.$expr_PathNode<$.TypeSet<$CreatedAt, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CreatedAt, $.Cardinality.Many), null);

export type $AuditableλShape = $.typeutil.flatten<$CreatedAtλShape & {
  "updated_at": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
}>;
type $Auditable = $.ObjectType<"default::Auditable", $AuditableλShape, null, [
  ...$CreatedAt['__exclusives__'],
]>;
const $Auditable = $.makeType<$Auditable>(_.spec, "331332de-8a32-11ef-a902-a510d5c36414", _.syntax.literal);

const Auditable: $.$expr_PathNode<$.TypeSet<$Auditable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Auditable, $.Cardinality.Many), null);

export type $TimedλShape = $.typeutil.flatten<$CreatedAtλShape & {
  "ends_at": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "duration": $.PropertyDesc<_std.$duration, $.Cardinality.One, false, true, false, false>;
}>;
type $Timed = $.ObjectType<"default::Timed", $TimedλShape, null, [
  ...$CreatedAt['__exclusives__'],
]>;
const $Timed = $.makeType<$Timed>(_.spec, "333bbc9a-8a32-11ef-b2c6-f947aceed76b", _.syntax.literal);

const Timed: $.$expr_PathNode<$.TypeSet<$Timed, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Timed, $.Cardinality.Many), null);



export { $CreatedAt, CreatedAt, $Auditable, Auditable, $Timed, Timed };

type __defaultExports = {
  "CreatedAt": typeof CreatedAt;
  "Auditable": typeof Auditable;
  "Timed": typeof Timed
};
const __defaultExports: __defaultExports = {
  "CreatedAt": CreatedAt,
  "Auditable": Auditable,
  "Timed": Timed
};
export default __defaultExports;
