// GENERATED by @edgedb/generate v0.5.6

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _default from "./default";
import type * as _users from "./users";
import type * as _std from "./std";
export type $EventType = {
  "WORKSHOP": $.$expr_Literal<$EventType>;
  "LECTURE": $.$expr_Literal<$EventType>;
  "MEETUP": $.$expr_Literal<$EventType>;
  "HACKATHON": $.$expr_Literal<$EventType>;
  "EXHIBITION": $.$expr_Literal<$EventType>;
  "WEBINAR": $.$expr_Literal<$EventType>;
} & $.EnumType<"event::EventType", ["WORKSHOP", "LECTURE", "MEETUP", "HACKATHON", "EXHIBITION", "WEBINAR"]>;
const EventType: $EventType = $.makeType<$EventType>(_.spec, "33414d72-8a32-11ef-9c75-57a21526521c", _.syntax.literal);

export type $EventλShape = $.typeutil.flatten<_default.$CreatedAtλShape & {
  "attendees": $.LinkDesc<_users.$User, $.Cardinality.AtLeastOne, {
    "@registered_at": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne>;
  }, false, false, false, false>;
  "organiser": $.LinkDesc<_users.$User, $.Cardinality.One, {}, false, false,  false, false>;
  "description": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "ends_at": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "starts_at": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, false>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "type": $.PropertyDesc<$EventType, $.Cardinality.One, false, false, false, false>;
}>;
type $Event = $.ObjectType<"event::Event", $EventλShape, null, [
  ..._default.$CreatedAt['__exclusives__'],
]>;
const $Event = $.makeType<$Event>(_.spec, "33415754-8a32-11ef-9f03-8d8b5b417329", _.syntax.literal);

const Event: $.$expr_PathNode<$.TypeSet<$Event, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Event, $.Cardinality.Many), null);



export { EventType, $Event, Event };

type __defaultExports = {
  "EventType": typeof EventType;
  "Event": typeof Event
};
const __defaultExports: __defaultExports = {
  "EventType": EventType,
  "Event": Event
};
export default __defaultExports;
