// GENERATED by @edgedb/generate v0.5.6

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _default from "./default";
import type * as _users from "./users";
import type * as _std from "./std";
export type $DeliveryMethod = {
  "IN_APP": $.$expr_Literal<$DeliveryMethod>;
  "EMAIL": $.$expr_Literal<$DeliveryMethod>;
} & $.EnumType<"notification::DeliveryMethod", ["IN_APP", "EMAIL"]>;
const DeliveryMethod: $DeliveryMethod = $.makeType<$DeliveryMethod>(_.spec, "33cfaf22-8a32-11ef-86e6-3fb6dfca8d9e", _.syntax.literal);

export type $NotificationType = {
  "GENERAL": $.$expr_Literal<$NotificationType>;
  "REFERRAL_SUCCESS": $.$expr_Literal<$NotificationType>;
  "NEW_ANNOUNCEMENT": $.$expr_Literal<$NotificationType>;
  "QUEUE_SLOT_ACTIVE": $.$expr_Literal<$NotificationType>;
} & $.EnumType<"notification::NotificationType", ["GENERAL", "REFERRAL_SUCCESS", "NEW_ANNOUNCEMENT", "QUEUE_SLOT_ACTIVE"]>;
const NotificationType: $NotificationType = $.makeType<$NotificationType>(_.spec, "3352e15e-8a32-11ef-940a-8fe7914f4e98", _.syntax.literal);

export type $AnnouncementλShape = $.typeutil.flatten<_default.$AuditableλShape & {
  "views": $.LinkDesc<_users.$User, $.Cardinality.Many, {
    "@viewed_at": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne>;
  }, false, false, false, false>;
  "content": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "title": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $Announcement = $.ObjectType<"notification::Announcement", $AnnouncementλShape, null, [
  ..._default.$Auditable['__exclusives__'],
]>;
const $Announcement = $.makeType<$Announcement>(_.spec, "332f8416-8a32-11ef-b813-758e8833527e", _.syntax.literal);

const Announcement: $.$expr_PathNode<$.TypeSet<$Announcement, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Announcement, $.Cardinality.Many), null);

export type $MailingListλShape = $.typeutil.flatten<_default.$AuditableλShape & {
  "description": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "subscribers": $.LinkDesc<_users.$User, $.Cardinality.Many, {}, false, true,  false, false>;
  "<mailing_list_subscriptions[is users::User]": $.LinkDesc<_users.$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<mailing_list_subscriptions[is users::Rep]": $.LinkDesc<_users.$Rep, $.Cardinality.Many, {}, false, false,  false, false>;
  "<mailing_list_subscriptions": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $MailingList = $.ObjectType<"notification::MailingList", $MailingListλShape, null, [
  ..._default.$Auditable['__exclusives__'],
]>;
const $MailingList = $.makeType<$MailingList>(_.spec, "333123d4-8a32-11ef-b3d1-5faf3bccbb8e", _.syntax.literal);

const MailingList: $.$expr_PathNode<$.TypeSet<$MailingList, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($MailingList, $.Cardinality.Many), null);

export type $NotificationλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "users": $.LinkDesc<_users.$User, $.Cardinality.Many, {
    "@read": $.PropertyDesc<_std.$bool, $.Cardinality.AtMostOne>;
  }, false, false, false, false>;
  "content": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "type": $.PropertyDesc<$NotificationType, $.Cardinality.One, false, false, false, false>;
}>;
type $Notification = $.ObjectType<"notification::Notification", $NotificationλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
]>;
const $Notification = $.makeType<$Notification>(_.spec, "3352e974-8a32-11ef-a81c-5765cdea10ce", _.syntax.literal);

const Notification: $.$expr_PathNode<$.TypeSet<$Notification, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Notification, $.Cardinality.Many), null);



export { DeliveryMethod, NotificationType, $Announcement, Announcement, $MailingList, MailingList, $Notification, Notification };

type __defaultExports = {
  "DeliveryMethod": typeof DeliveryMethod;
  "NotificationType": typeof NotificationType;
  "Announcement": typeof Announcement;
  "MailingList": typeof MailingList;
  "Notification": typeof Notification
};
const __defaultExports: __defaultExports = {
  "DeliveryMethod": DeliveryMethod,
  "NotificationType": NotificationType,
  "Announcement": Announcement,
  "MailingList": MailingList,
  "Notification": Notification
};
export default __defaultExports;
