// GENERATED by @edgedb/generate v0.5.3

import type {Executor} from "edgedb";

export type SearchUsersArgs = {
  readonly "limit": number;
  readonly "query": string;
};

export type SearchUsersReturns = Array<{
  "id": string;
  "pronouns": string | null;
  "email": string;
  "display_name": string;
  "username": string;
  "ucard_number": number;
  "profile_picture": string | null;
  "created_at": Date;
  "roles": Array<{
    "id": string;
    "name": string;
  }>;
}>;

export function searchUsers(client: Executor, args: SearchUsersArgs): Promise<SearchUsersReturns> {
  return client.query(`\
with users := (
    select users::User {
        similarty := ext::pg_trgm::word_similarity(
            <str>$query,
            (
                "000" ++ to_str(.ucard_number) ++ " " ++
                .username ++ " " ++
                .email ++ " " ++
                .display_name
            )
        )
    }
    filter .similarty > 0.3
    order by .similarty desc
    limit max({min({<int64>$limit, 100}), 1})
)
select users {
    id,
    pronouns,
    email,
    display_name,
    username,
    ucard_number,
    profile_picture,
    created_at,
    roles: {
        id,
        name,
    },
}`, args);

}
