apiVersion: v1
kind: Service
metadata:
  name: forge-service
  namespace: ignis
  labels:
    app: forge
    app.kubernetes.io/name: forge
    app.kubernetes.io/part-of: ignis
spec:
  selector:
    app: forge
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http 
  type: ClusterIP 