name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-restart:
    runs-on: self-hosted

    steps:
      - name: Pull the latest changes
        working-directory: /home/iforge/ignis/
        run: git pull

      - name: Throw up the maintenance page
        run: touch /home/iforge/ignis-config/file_flags/maintenance_mode/enabled

      - name: Build the project
        working-directory: /home/iforge/ignis/
        run: turbo build

      - name: Restart systemd service
        run: systemctl restart anvil.service

      - name: Remove maintenance page
        run: rm /home/iforge/ignis-config/file_flags/maintenance_mode/enabled
