name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-restart:
    runs-on: self-hosted

    steps:
      - name: Pull the latest changes
        working-directory: /home/iforge/ignis/
        run: git pull

      - name: Notify Discord Maintenance Start
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_ANNOUCE_WEBHOOK_URL }}
          content: "Ignis Entering Maintenance Mode"

      - name: Throw up the maintenance page
        run: touch /home/iforge/ignis-config/file_flags/maintenance_mode/enabled

      - name: Sort out env for pnpm
        run: |
          echo "/home/iforge/.nvm/versions/node/v20.11.0/bin" >> $GITHUB_PATH
          echo "/home/iforge/.local/share/pnpm" >> $GITHUB_PATH

      - name: Install Packages
        working-directory: /home/iforge/ignis
        run: pnpm i

      - name: Build the project
        working-directory: /home/iforge/ignis/
        run: turbo build

      - name: Restart systemd service
        run: /home/iforge/ignis-config/scripts/start_or_restart.sh

      - name: Remove maintenance page
        run: rm /home/iforge/ignis-config/file_flags/maintenance_mode/enabled

      - name: Notify Discord Maintenance Start
        uses: tsickert/discord-webhook@v6.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_ANNOUCE_WEBHOOK_URL }}
          content: "Ignis Exiting Maintenance Mode..."